1.Introduction: A customer wants to open a restaurant in Bangalore. He is looking for a potential neigborhood in Bangalore having many companies with good employee size, to open his restaurant.

2.Data Section-Preparing the three datasets

Importing Dataset1.xlsx from local computer and converitng it to a pandas dataframe

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_3fa636d9b3f646ac8f3bb5de175890e6 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='r1O87ZSHhNgI9W4mn1UaavErqBTxdY1bjcrlqevvEnqb',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_3fa636d9b3f646ac8f3bb5de175890e6.get_object(Bucket='businessproblemibmapplieddatascie-donotdelete-pr-dtdt3j8tjafjfu',Key='Dataset1.xlsx')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_0 = pd.read_excel(body)
df_data_0.head()

,Country,Pincode,Area,Bangalore-Division,Latitude,Longitude
0,IN,560001,Bangalore G.P.O.,Bangalore North,12.9914,77.5944
1,IN,560001,Legislators Home,Bangalore North,12.9914,77.5944
2,IN,560001,Vasanthanagar,Bangalore North,12.9914,77.5944
3,IN,560001,Mahatma Gandhi Road,Bangalore North,12.9914,77.5944
4,IN,560001,Vidhana Soudha,Bangalore North,12.9914,77.5944

In [3]:
dataset1=df_data_0
dataset1

,Country,Pincode,Area,Bangalore-Division,Latitude,Longitude
0,IN,560001,Bangalore G.P.O.,Bangalore North,12.9914,77.5944
1,IN,560001,Legislators Home,Bangalore North,12.9914,77.5944
2,IN,560001,Vasanthanagar,Bangalore North,12.9914,77.5944
3,IN,560001,Mahatma Gandhi Road,Bangalore North,12.9914,77.5944
4,IN,560001,Vidhana Soudha,Bangalore North,12.9914,77.5944
5,IN,560001,Rajbhavan (Bangalore),Bangalore North,12.9914,77.5944
6,IN,560001,HighCourt,Bangalore North,12.9914,77.5944
7,IN,560001,Cubban Road,Bangalore North,12.9914,77.5944
8,IN,560001,Bangalore Bazaar,Bangalore North,12.9914,77.5944
9,IN,560001,CMM Court Complex,Bangalore North,12.9914,77.5944
10,IN,560001,Dr. Ambedkar Veedhi,Bangalore North,12.9914,77.5944
11,IN,560002,Bangalore City,Bangalore North,12.9719,77.5937
12,IN,560002,Bangalore Corporation Building,Bangalore South,12.9719,77.5937
13,IN,560002,Sri Jayachamarajendra Road,Bangalore South,12.9719,77.5937
14,IN,560003,Palace Guttahalli,Bangalore North,13.0097,77.5648
15,IN,560003,Malleswaram,Bangalore North,13.0097,77.5648
16,IN,560003,Swimming Pool Extn,Bangalore North,13.0097,77.5648
17,IN,560003,Vyalikaval Extn,Bangalore North,13.0097,77.5648
18,IN,560004,Pampamahakavi Road,Bangalore South,13.5207,76.0303
19,IN,560004,Thyagarajnagar,Bangalore South,13.5207,76.0303
20,IN,560004,Mavalli,Bangalore South,14.0998,74.4891
21,IN,560004,Basavanagudi,Bangalore South,12.9417,77.5714
22,IN,560005,Fraser Town,Bangalore North,13.2029,76.9627
23,IN,560006,J.C.Nagar,Bangalore North,13.2029,76.9627
24,IN,560006,Training Command IAF,Bangalore North,13.2029,76.9627
25,IN,560007,Agram,Bangalore South,13.2029,76.9627
26,IN,560007,Air Force Hospital,Bangalore North,13.2029,76.9627
27,IN,560008,Hulsur Bazaar,Bangalore North,13.2029,76.9627
28,IN,560008,H.A.L II Stage,Bangalore North,13.2029,76.9627
29,IN,560009,K. G. Road,Bangalore North,13.2029,76.9627
...,...,...,...,...,...,...
203,IN,560087,Gunjur,Bangalore North,12.9316,77.6041
204,IN,560090,Tarabanahalli,Bangalore North,13.0068,77.5971
205,IN,560091,Herohalli,Bangalore North,13.0583,77.5732
206,IN,560091,Bapagrama,Bangalore North,13.0583,77.5732
207,IN,560091,Viswaneedam,Bangalore North,13.0583,77.5732
208,IN,560091,Herohalli,Bangalore north,13.0583,77.5732
209,IN,560092,Amruthahalli,Bangalore North,13.0597,77.5831
210,IN,560092,Byatarayanapura,Bangalore North,13.0611,77.5930
211,IN,560092,Kodigehalli,Bangalore North,13.0583,77.5732
212,IN,560092,Sahakaranagar P.O,Bangalore North,13.0597,77.5831
213,IN,560093,C.V.Raman Nagar,Bangalore North,13.0068,77.5971
214,IN,560094,ISRO Anthariksha Bhavan,Bangalore North,13.0068,77.5971
215,IN,560094,R.M.V. Extension II Stage,Bangalore North,13.0068,77.5971
216,IN,560095,Koramangala VI Bk,Bangalore South,13.0068,77.5971
217,IN,560096,Nandinilayout,Bangalore North,13.0134,77.5361
218,IN,560097,Chikkabettahalli,Bangalore North,13.0814,77.5566
219,IN,560097,Vidyaranyapura,Bangalore North,13.0814,77.5566
220,IN,560098,Rajarajeshwarinagar,Bangalore South,13.1195,77.5837
221,IN,560098,Kenchanahalli,Bangalore South,13.1195,77.5837
222,IN,560099,Bommasandra Industrial Estate,Bangalore South,12.8311,77.6804
223,IN,560099,Hebbagodi,Bangalore South,12.8263,77.6809
224,IN,560099,Muthanallur,Bangalore South,12.8311,77.6804
225,IN,560100,Electronics City,Bangalore South,12.8458,77.6727
226,IN,560100,Wipro Limited,Bangalore South,12.8458,77.6727
227,IN,560102,HSR Layout,Bangalore South,13.1791,77.0942
228,IN,560103,Bellandur,Bangalore South,12.9255,77.6765
229,IN,560103,Panathur,Bangalore South,12.9255,77.6765
230,IN,560104,Hampinagar,Bangalore North,13.1791,77.0942
231,IN,560109,Thalaghattapura,Bangalore South,13.1791,77.0942
232,IN,560110,Ullalu Upanagar,Bangalore North,13.1791,77.0942

Importing Dataset2.xlsx from local computer.

In [4]:
body = client_3fa636d9b3f646ac8f3bb5de175890e6.get_object(Bucket='businessproblemibmapplieddatascie-donotdelete-pr-dtdt3j8tjafjfu',Key='Dataset2.xlsx')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_excel(body)
df_data_2.head()

,Pincode,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,560001,157,90,91,54,22,14,8,7
1,560002,47,23,13,6,0,2,0,1
2,560003,54,22,16,5,2,1,0,0
3,560004,53,28,27,10,0,2,1,1
4,560005,37,14,6,0,1,0,1,1

In [5]:
dataset2=df_data_2
dataset2

,Pincode,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,560001,157,90,91,54,22,14,8,7
1,560002,47,23,13,6,0,2,0,1
2,560003,54,22,16,5,2,1,0,0
3,560004,53,28,27,10,0,2,1,1
4,560005,37,14,6,0,1,0,1,1
5,560006,1,1,1,1,0,0,0,0
6,560007,0,0,0,0,0,0,0,0
7,560008,101,57,38,16,2,3,0,0
8,560009,30,13,14,2,1,0,0,0
9,560010,64,31,19,6,6,0,0,1
10,560011,62,38,22,7,4,0,0,0
11,560012,3,0,0,2,0,1,0,0
12,560013,7,5,7,1,0,0,0,1
13,560014,2,0,0,0,0,0,0,0
14,560015,6,1,1,0,0,0,0,0
15,560016,20,15,6,5,1,1,0,1
16,560017,36,15,16,7,0,3,0,1
17,560018,13,7,8,3,0,0,0,0
18,560019,6,2,4,1,0,0,0,1
19,560020,33,15,8,5,3,0,0,1
20,560021,19,1,1,0,0,0,0,0
21,560022,30,23,17,10,2,5,0,1
22,560023,3,7,1,2,0,0,0,0
23,560024,16,14,11,5,0,2,1,0
24,560025,93,47,50,16,14,6,1,3
25,560026,21,12,6,3,0,0,0,0
26,560027,38,30,36,9,7,1,1,2
27,560029,28,15,17,6,7,4,3,2
28,560030,13,11,4,0,0,0,0,2
29,560032,0,23,9,3,1,0,1,0
...,...,...,...,...,...,...,...,...,...
67,560073,2,6,2,0,0,2,0,0
68,560074,6,7,11,0,2,0,0,0
69,560075,38,14,8,2,0,2,0,0
70,560076,72,35,26,10,6,3,2,5
71,560077,12,5,7,2,0,0,0,0
72,560078,100,53,43,14,8,1,0,0
73,560079,45,14,10,2,0,0,0,0
74,560080,22,16,13,3,1,2,0,0
75,560082,16,15,11,4,0,0,0,0
76,560083,8,4,5,1,0,0,0,0
77,560084,20,5,2,0,0,0,0,0
78,560085,34,13,13,2,0,0,0,0
79,560086,18,10,10,2,1,1,0,1
80,560087,4,2,2,2,2,3,0,0
81,560090,7,5,1,0,0,0,0,0
82,560091,38,8,15,1,0,0,0,0
83,560092,21,14,9,5,0,1,0,1
84,560093,19,5,7,9,5,0,1,0
85,560094,29,18,7,4,3,0,0,1
86,560095,67,44,36,14,2,0,2,2
87,560096,8,1,7,0,0,0,0,0
88,560097,16,3,5,1,1,0,0,0
89,560098,16,6,5,0,1,0,0,0
90,560099,24,22,40,11,7,3,2,0
91,560100,48,38,35,23,6,6,2,5
92,560102,98,64,46,11,5,0,0,1
93,560103,22,28,27,21,7,2,5,7
94,560104,5,0,2,1,0,0,0,0
95,560109,0,0,0,0,0,0,0,0
96,560110,1,0,0,0,0,0,0,0

Preparing Dataset3 - Dataset1 followed by addition of Foursquare data.

i. Removing columns designated as 'Country','Pincode' and 'Bangalore-Division' from Dataset1.

In [6]:
df=dataset1.drop(['Country','Pincode','Bangalore-Division'], axis=1)

In [7]:
df

                               Area  Latitude  Longitude
0                  Bangalore G.P.O.   12.9914    77.5944
1                  Legislators Home   12.9914    77.5944
2                     Vasanthanagar   12.9914    77.5944
3               Mahatma Gandhi Road   12.9914    77.5944
4                    Vidhana Soudha   12.9914    77.5944
5             Rajbhavan (Bangalore)   12.9914    77.5944
6                         HighCourt   12.9914    77.5944
7                       Cubban Road   12.9914    77.5944
8                  Bangalore Bazaar   12.9914    77.5944
9                 CMM Court Complex   12.9914    77.5944
10              Dr. Ambedkar Veedhi   12.9914    77.5944
11                   Bangalore City   12.9719    77.5937
12   Bangalore Corporation Building   12.9719    77.5937
13       Sri Jayachamarajendra Road   12.9719    77.5937
14                Palace Guttahalli   13.0097    77.5648
15                      Malleswaram   13.0097    77.5648
16               Swimming Pool Extn   13.0097    77.5648
17                  Vyalikaval Extn   13.0097    77.5648
18               Pampamahakavi Road   13.5207    76.0303
19                   Thyagarajnagar   13.5207    76.0303
20                          Mavalli   14.0998    74.4891
21                     Basavanagudi   12.9417    77.5714
22                      Fraser Town   13.2029    76.9627
23                        J.C.Nagar   13.2029    76.9627
24             Training Command IAF   13.2029    76.9627
25                            Agram   13.2029    76.9627
26               Air Force Hospital   13.2029    76.9627
27                    Hulsur Bazaar   13.2029    76.9627
28                   H.A.L II Stage   13.2029    76.9627
29                       K. G. Road   13.2029    76.9627
..                              ...       ...        ...
203                          Gunjur   12.9316    77.6041
204                   Tarabanahalli   13.0068    77.5971
205                       Herohalli   13.0583    77.5732
206                       Bapagrama   13.0583    77.5732
207                     Viswaneedam   13.0583    77.5732
208                       Herohalli   13.0583    77.5732
209                    Amruthahalli   13.0597    77.5831
210                 Byatarayanapura   13.0611    77.5930
211                     Kodigehalli   13.0583    77.5732
212               Sahakaranagar P.O   13.0597    77.5831
213                 C.V.Raman Nagar   13.0068    77.5971
214         ISRO Anthariksha Bhavan   13.0068    77.5971
215       R.M.V. Extension II Stage   13.0068    77.5971
216               Koramangala VI Bk   13.0068    77.5971
217                   Nandinilayout   13.0134    77.5361
218                Chikkabettahalli   13.0814    77.5566
219                  Vidyaranyapura   13.0814    77.5566
220             Rajarajeshwarinagar   13.1195    77.5837
221                   Kenchanahalli   13.1195    77.5837
222   Bommasandra Industrial Estate   12.8311    77.6804
223                       Hebbagodi   12.8263    77.6809
224                     Muthanallur   12.8311    77.6804
225                Electronics City   12.8458    77.6727
226                   Wipro Limited   12.8458    77.6727
227                      HSR Layout   13.1791    77.0942
228                       Bellandur   12.9255    77.6765
229                        Panathur   12.9255    77.6765
230                      Hampinagar   13.1791    77.0942
231                 Thalaghattapura   13.1791    77.0942
232                 Ullalu Upanagar   13.1791    77.0942

[233 rows x 3 columns]

ii.Grouping data by Longitude and Latitude and joining the areas.

In [8]:
long_lat_data=df.groupby(['Longitude','Latitude'],sort=False).agg(', '.join)
long_lat_data.reset_index(inplace=True)
long_lat_data

    Longitude  Latitude                                               Area
0     77.5944   12.9914  Bangalore G.P.O., Legislators Home, Vasanthana...
1     77.5937   12.9719  Bangalore City, Bangalore Corporation Building...
2     77.5648   13.0097  Palace Guttahalli, Malleswaram, Swimming Pool ...
3     76.0303   13.5207                 Pampamahakavi Road, Thyagarajnagar
4     74.4891   14.0998                                            Mavalli
5     77.5714   12.9417                                       Basavanagudi
6     76.9627   13.2029  Fraser Town, J.C.Nagar, Training Command IAF, ...
7     77.5491   12.9847  Rajajinagar, Industrial Estate (Bangalore), Ra...
8     76.2752   15.8266  Jayangar III Block, Madhavan Park, Science Ins...
9     77.5474   13.0448                                          Jalahalli
10    73.7291   21.4504                                    Vimanapura, NAL
11    77.5789   12.9879                                      Seshadripuram
12    77.5625   12.9879                         Gayathrinagar, Srirampuram
13    77.4484   13.1100  Yeshwanthpur Bazar, Yeswanthpura, Anandnagar (...
14    77.5489   12.9750                                        Magadi Road
15    77.6025   12.9634  Museum Road, Richmond Town, CMP Centre And School
16    77.5952   12.9506      Sampangiramnagar, Wilson Garden, Shanthinagar
17    76.8024   13.7952                      Tavarekere, Dharmaram College
18    77.6079   12.9440                                            Adugodi
19    77.6153   12.9380  R T Nagar, Kanakanagar, P&T Col. Kavalbyrasand...
20    77.6227   12.9320  Agara, Koramangala, Koramangala I Block, St. J...
21    77.4920   12.6859  Chandra Lay Out, Vijayanagar (Bangalore), Vija...
22    77.5885   12.9278                  Jayanagar, Tilaknagar (Bangalore)
23    77.6487   13.0158   Horamavu, Banaswadi, Jalavayuvihar, Kalyananagar
24    77.6226   13.0360           Nagawara, Arabic College, Venkateshapura
25    77.6044   12.9985                                        Benson Town
26    77.7164   12.9944                                              Hoodi
27    77.6869   12.9923                                       Mahadevapura
28    76.5761   10.8368  Mundur, Bidrahalli, Thambuchetty palya, Virgon...
29    77.5609   13.0323  Dasarahalli(Srinagar), State Bank Of Mysore Co...
..        ...       ...                                                ...
38    77.6209   12.9240                                           Madivala
39    77.6299   12.8931                                       Bommanahalli
40    77.5798   12.9229  Tyagrajnagar, B Sk II Stage, Padmanabhnagar, J...
41    77.6391   12.9617                                             Domlur
42    77.5113   12.9801                                         Nagarbhavi
43    77.5978   12.8939  Bannerghatta Road, Mount St Joseph, Bilekahall...
44    77.6001   12.9106                                        Mico Layout
45    77.5709   12.9020                                     Yelachenahalli
46    77.5617   12.9057                                 Kumaraswamy Layout
47    77.5663   12.9038                      J P Nagar, JP Nagar III Phase
48    77.5806   13.0104                                     Sadashivanagar
49    77.5053   12.7717                                             Bolare
50    77.5896   12.8608                                          Gottigere
51    77.6011   12.9023                                       Bannerghatta
52    77.6374   13.0096  Lingarajapuram, Kacharakanahalli, St. Thomas Town
53    77.5930   13.0611                   Byatarayanapura, Byatarayanapura
54    77.5523   12.9299                                        Kathriguppe
55    77.5726   12.9955  Girinagar (Bangalore), Hosakerehalli, Banashan...
56    77.6041   12.9316  West of Chord Road II stage, Mahalakshmipuram ...
57    77.5971   13.0068  Tarabanahalli, C.V.Raman Nagar, ISRO Anthariks...
58    77.5732   13.0583  Herohalli, Bapagrama, Viswaneedam, Herohalli, ...
59    77.5831   13.0597                    Amruthahalli, Sahakaranagar P.O
60    77.5361   13.0134                                      Nandinilayout
61    77.5566   13.0814                   Chikkabettahalli, Vidyaranyapura
62    77.5837   13.1195                 Rajarajeshwarinagar, Kenchanahalli
63    77.6804   12.8311         Bommasandra Industrial Estate, Muthanallur
64    77.6809   12.8263                                          Hebbagodi
65    77.6727   12.8458                    Electronics City, Wipro Limited
66    77.0942   13.1791  HSR Layout, Hampinagar, Thalaghattapura, Ullal...
67    77.6765   12.9255                                Bellandur, Panathur

[68 rows x 3 columns]

iii. Seting up Foursqaure credentials

In [9]:
CLIENT_ID = 'NJO5CSY5OPUDPDP51UFVB0TOIKJW51G21KUKGU3QIZLTEE5I' # your Foursquare ID
CLIENT_SECRET = 'M50DCNP1YIGF30YIPMKLKQ5SHLBLGHPKKDCBXPDSC1M3LPPX' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: NJO5CSY5OPUDPDP51UFVB0TOIKJW51G21KUKGU3QIZLTEE5I
CLIENT_SECRET:M50DCNP1YIGF30YIPMKLKQ5SHLBLGHPKKDCBXPDSC1M3LPPX

iv. Trial-Generating data for pair of longitude and latitude using Foursqaure data.

In [10]:
radius = 1000
search_query1='Food'

In [11]:
longitude =long_lat_data.loc[11,'Longitude']
latitude =long_lat_data.loc[11,'Latitude']
LIMIT=2000
longitude

77.5789

In [12]:
url='https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query1, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=NJO5CSY5OPUDPDP51UFVB0TOIKJW51G21KUKGU3QIZLTEE5I&client_secret=M50DCNP1YIGF30YIPMKLKQ5SHLBLGHPKKDCBXPDSC1M3LPPX&ll=12.9879,77.5789&v=20180605&query=Food&radius=1000&limit=2000'

In [13]:
import json
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

In [15]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5f15ec2faf2b4b31375ab395'},
 'response': {'venues': [{'id': '4c15e70e7f7f2d7f4725e368',
    'name': 'Food Court',
    'location': {'address': 'Mantri Square, Malleshwaram',
     'crossStreet': '1, Sampige Rd',
     'lat': 12.991646212171805,
     'lng': 77.57061710566572,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.991646212171805,
       'lng': 77.57061710566572}],
     'distance': 990,
     'cc': 'IN',
     'city': 'Bangalore',
     'state': 'Karnātaka',
     'country': 'India',
     'formattedAddress': ['Mantri Square, Malleshwaram (1, Sampige Rd)',
      'Bangalore',
      'Karnātaka',
      'India']},
    'categories': [{'id': '4bf58dd8d48988d120951735',
      'name': 'Food Court',
      'pluralName': 'Food Courts',
      'shortName': 'Food Court',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_foodcourt_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '58038f61d67c97767aed42d3',
    'name': 'food shack',
    'location': {'lat': 12.989167,
     'lng': 77.57869,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.989167,
       'lng': 77.57869}],
     'distance': 142,
     'cc': 'IN',
     'country': 'India',
     'formattedAddress': ['India']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '5985918df0ca957f7ef97eef',
    'name': 'Food Point',
    'location': {'lat': 12.988431,
     'lng': 77.57672,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.988431,
       'lng': 77.57672}],
     'distance': 243,
     'postalCode': '560020',
     'cc': 'IN',
     'city': 'Bangalore',
     'state': 'Karnātaka',
     'country': 'India',
     'formattedAddress': ['Bangalore 560020', 'Karnātaka', 'India']},
    'categories': [{'id': '4bf58dd8d48988d16e941735',
      'name': 'Fast Food Restaurant',
      'pluralName': 'Fast Food Restaurants',
      'shortName': 'Fast Food',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '52ee437b498ef60e403eb9e8',
    'name': 'Sagar food mall',
    'location': {'lat': 12.988262880536288,
     'lng': 77.57710704647988,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.988262880536288,
       'lng': 77.57710704647988}],
     'distance': 198,
     'cc': 'IN',
     'country': 'India',
     'formattedAddress': ['India']},
    'categories': [{'id': '4bf58dd8d48988d16e941735',
      'name': 'Fast Food Restaurant',
      'pluralName': 'Fast Food Restaurants',
      'shortName': 'Fast Food',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '4e7c922c45ddca1aee62a780',
    'name': 'General Food Additives',
    'location': {'address': '175/3, 1st main road',
     'crossStreet': 'Seshadripuram ( opp HDFC bank)',
     'lat': 12.99138268874908,
     'lng': 77.57510342891321,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.99138268874908,
       'lng': 77.57510342891321}],
     'distance': 565,
     'postalCode': '560020',
     'cc': 'IN',
     'city': 'Bangalore',
     'state': 'Karnātaka',
     'country': 'India',
     'formattedAddress': ['175/3, 1st main road (Seshadripuram ( opp HDFC bank))',
      'Bangalore 560020',
      'Karnātaka',
      'India']},
    'categories': [],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '5736e2ea498eac23d5bdfb3b',
    'name': 'forgotten food',
    'location': {'lat': 12.990248,
     'lng': 77.571838,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.990248,
       'lng': 77.571838}],
     'distance': 809,
     'cc': 'IN',
     'country': 'India',
     'formattedAddress': ['India']},
    'categories': [{'id': '52e81612bcbc57f1066b7a00',
      'name': 'Comfort Food Restaurant',
      'pluralName': 'Comfort Food Restaurants',
      'shortName': 'Comfort Food',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '4f267c17e4b0085e4bf50265',
    'name': 'Commissionerate of Food Safety',
    'location': {'address': 'Anandrao Circle',
     'lat': 12.9814657,
     'lng': 77.5736428,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.9814657,
       'lng': 77.5736428}],
     'distance': 915,
     'cc': 'IN',
     'city': 'Bangalore',
     'state': 'Karnātaka',
     'country': 'India',
     'formattedAddress': ['Anandrao Circle',
      'Bangalore',
      'Karnātaka',
      'India']},
    'categories': [],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '4f2d4abde4b0dbffdc0e1c0d',
    'name': 'Vegbynature- food courts',
    'location': {'lat': 12.991557678944046,
     'lng': 77.57106810263681,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.991557678944046,
       'lng': 77.57106810263681}],
     'distance': 942,
     'cc': 'IN',
     'country': 'India',
     'formattedAddress': ['India']},
    'categories': [{'id': '4bf58dd8d48988d10f941735',
      'name': 'Indian Restaurant',
      'pluralName': 'Indian Restaurants',
      'shortName': 'Indian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/indian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '5252354311d233ad1b7a27ad',
    'name': 'Golden Landmark Food,Banglore',
    'location': {'lat': 12.980436325073242,
     'lng': 77.57380676269531,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.980436325073242,
       'lng': 77.57380676269531}],
     'distance': 997,
     'cc': 'IN',
     'country': 'India',
     'formattedAddress': ['India']},
    'categories': [{'id': '4bf58dd8d48988d10f941735',
      'name': 'Indian Restaurant',
      'pluralName': 'Indian Restaurants',
      'shortName': 'Indian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/indian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '58689e58b210145ef673ca80',
    'name': 'Healthy Food Tech',
    'location': {'lat': 12.995673,
     'lng': 77.572556,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.995673,
       'lng': 77.572556}],
     'distance': 1105,
     'cc': 'IN',
     'country': 'India',
     'formattedAddress': ['India']},
    'categories': [{'id': '4bf58dd8d48988d1ff941735',
      'name': 'Miscellaneous Shop',
      'pluralName': 'Miscellaneous Shops',
      'shortName': 'Shop',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/default_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '4e60964262e13e3bcdd1c175',
    'name': 'Palette, The food court',
    'location': {'address': '4th floor, Mantri square',
     'crossStreet': 'Malleshwaram',
     'lat': 12.991731346390726,
     'lng': 77.57043564595148,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.991731346390726,
       'lng': 77.57043564595148}],
     'distance': 1012,
     'cc': 'IN',
     'city': 'Bangalore',
     'state': 'Karnātaka',
     'country': 'India',
     'formattedAddress': ['4th floor, Mantri square (Malleshwaram)',
      'Bangalore',
      'Karnātaka',
      'India']},
    'categories': [],
    'referralId': 'v-1595272289',
    'hasPerk': False},
   {'id': '4f6609eae4b036e3e96bb5e9',
    'name': 'Kaati Zone',
    'location': {'address': 'Mantri Mall Food Court',
     'lat': 12.991846164008463,
     'lng': 77.57040766106077,
     'labeledLatLngs': [{'label': 'display',
       'lat': 12.991846164008463,
       'lng': 77.57040766106077}],
     'distance': 1020,
     'cc': 'IN',
     'state': 'Karnātaka',
     'country': 'India',
     'formattedAddress': ['Mantri Mall Food Court', 'Karnātaka', 'India']},
    'categories': [{'id': '4bf58dd8d48988d16e941735',
      'name': 'Fast Food Restaurant',
      'pluralName': 'Fast Food Restaurants',
      'shortName': 'Fast Food',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1595272289',
    'hasPerk': False}]}}

In [16]:
# assign relevant part of JSON to venues
V1= results['response']['venues']
dataframe = json_normalize(V1)
V1=dataframe['name']
V1

0                         Food Court
1                         food shack
2                         Food Point
3                    Sagar food mall
4             General Food Additives
5                     forgotten food
6     Commissionerate of Food Safety
7           Vegbynature- food courts
8      Golden Landmark Food,Banglore
9                  Healthy Food Tech
10           Palette, The food court
11                        Kaati Zone
Name: name, dtype: object

In [17]:
V1.count()

12

v.Running a for loop to check all the Food Outlets within 2000m(2km) of all longitudes and latitudes.

In [18]:
data=[]
for i in range (68):
    radius = 2000
    search_query='Food'
    longitude =long_lat_data.loc[i,'Longitude']
    latitude =long_lat_data.loc[i,'Latitude']
    LIMIT=5000
    url='https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
    results = requests.get(url).json()
    V1= results['response']['venues']
    dataframe = json_normalize(V1)
    if 'name' in dataframe:
         V1=dataframe['name'].count()
         f1=(V1,longitude,latitude)
         data.append(f1)
         print(V1,longitude,latitude)
    else:
         f1=(0, longitude,latitude)
         data.append(f1)
         print (0,longitude,latitude)

31 77.5944 12.9914
49 77.5937 12.9719
47 77.5648 13.0097
0 76.0303 13.5207
0 74.4891 14.0998
35 77.5714 12.9417
0 76.9627 13.2029
37 77.5491 12.9847
0 76.2752 15.8266
9 77.5474 13.0448
0 73.7291 21.4504
42 77.5789 12.9879
44 77.5625 12.9879
0 77.4484 13.11
32 77.5489 12.975
48 77.6025 12.9634
31 77.5952 12.9506
0 76.8024 13.7952
50 77.6079 12.944
50 77.6153 12.938
50 77.6227 12.932
0 77.492 12.6859
50 77.5885 12.9278
28 77.6487 13.0158
20 77.6226 13.036
37 77.6044 12.9985
20 77.7164 12.9944
21 77.6869 12.9923
0 76.5761 10.8368
40 77.5609 13.0323
8 77.481 12.9121
0 77.7432 12.769
0 78.0988 12.3477
10 77.5963 13.1013
1 78.6014 11.5941
22 77.7473 12.9716
3 77.6279 12.8706
23 77.626 12.8949
50 77.6209 12.924
19 77.6299 12.8931
50 77.5798 12.9229
50 77.6391 12.9617
9 77.5113 12.9801
48 77.5978 12.8939
50 77.6001 12.9106
21 77.5709 12.902
17 77.5617 12.9057
19 77.5663 12.9038
37 77.5806 13.0104
0 77.5053 12.7717
12 77.5896 12.8608
50 77.6011 12.9023
32 77.6374 13.0096
16 77.593 13.0611
21 77.5523 12.9299
37 77.5726 12.9955
50 77.6041 12.9316
33 77.5971 13.0068
19 77.5732 13.0583
18 77.5831 13.0597
22 77.5361 13.0134
7 77.5566 13.0814
5 77.5837 13.1195
19 77.6804 12.8311
9 77.6809 12.8263
44 77.6727 12.8458
0 77.0942 13.1791
33 77.6765 12.9255

In [19]:
data

[(31, 77.5944, 12.9914),
 (49, 77.5937, 12.9719),
 (47, 77.5648, 13.0097),
 (0, 76.0303, 13.5207),
 (0, 74.4891, 14.0998),
 (35, 77.5714, 12.9417),
 (0, 76.9627, 13.2029),
 (37, 77.5491, 12.9847),
 (0, 76.2752, 15.8266),
 (9, 77.5474, 13.0448),
 (0, 73.7291, 21.4504),
 (42, 77.5789, 12.9879),
 (44, 77.5625, 12.9879),
 (0, 77.4484, 13.11),
 (32, 77.5489, 12.975),
 (48, 77.6025, 12.9634),
 (31, 77.5952, 12.9506),
 (0, 76.8024, 13.7952),
 (50, 77.6079, 12.944),
 (50, 77.6153, 12.938),
 (50, 77.6227, 12.932),
 (0, 77.492, 12.6859),
 (50, 77.5885, 12.9278),
 (28, 77.6487, 13.0158),
 (20, 77.6226, 13.036),
 (37, 77.6044, 12.9985),
 (20, 77.7164, 12.9944),
 (21, 77.6869, 12.9923),
 (0, 76.5761, 10.8368),
 (40, 77.5609, 13.0323),
 (8, 77.481, 12.9121),
 (0, 77.7432, 12.769),
 (0, 78.0988, 12.3477),
 (10, 77.5963, 13.1013),
 (1, 78.6014, 11.5941),
 (22, 77.7473, 12.9716),
 (3, 77.6279, 12.8706),
 (23, 77.626, 12.8949),
 (50, 77.6209, 12.924),
 (19, 77.6299, 12.8931),
 (50, 77.5798, 12.9229),
 (50, 77.6391, 12.9617),
 (9, 77.5113, 12.9801),
 (48, 77.5978, 12.8939),
 (50, 77.6001, 12.9106),
 (21, 77.5709, 12.902),
 (17, 77.5617, 12.9057),
 (19, 77.5663, 12.9038),
 (37, 77.5806, 13.0104),
 (0, 77.5053, 12.7717),
 (12, 77.5896, 12.8608),
 (50, 77.6011, 12.9023),
 (32, 77.6374, 13.0096),
 (16, 77.593, 13.0611),
 (21, 77.5523, 12.9299),
 (37, 77.5726, 12.9955),
 (50, 77.6041, 12.9316),
 (33, 77.5971, 13.0068),
 (19, 77.5732, 13.0583),
 (18, 77.5831, 13.0597),
 (22, 77.5361, 13.0134),
 (7, 77.5566, 13.0814),
 (5, 77.5837, 13.1195),
 (19, 77.6804, 12.8311),
 (9, 77.6809, 12.8263),
 (44, 77.6727, 12.8458),
 (0, 77.0942, 13.1791),
 (33, 77.6765, 12.9255)]

vi.Converting the data into a pandas dataframe designating it as 'dataset3'.

In [20]:
dataset3=pd.DataFrame(data=data)
dataset3

     0        1        2
0   31  77.5944  12.9914
1   49  77.5937  12.9719
2   47  77.5648  13.0097
3    0  76.0303  13.5207
4    0  74.4891  14.0998
5   35  77.5714  12.9417
6    0  76.9627  13.2029
7   37  77.5491  12.9847
8    0  76.2752  15.8266
9    9  77.5474  13.0448
10   0  73.7291  21.4504
11  42  77.5789  12.9879
12  44  77.5625  12.9879
13   0  77.4484  13.1100
14  32  77.5489  12.9750
15  48  77.6025  12.9634
16  31  77.5952  12.9506
17   0  76.8024  13.7952
18  50  77.6079  12.9440
19  50  77.6153  12.9380
20  50  77.6227  12.9320
21   0  77.4920  12.6859
22  50  77.5885  12.9278
23  28  77.6487  13.0158
24  20  77.6226  13.0360
25  37  77.6044  12.9985
26  20  77.7164  12.9944
27  21  77.6869  12.9923
28   0  76.5761  10.8368
29  40  77.5609  13.0323
..  ..      ...      ...
38  50  77.6209  12.9240
39  19  77.6299  12.8931
40  50  77.5798  12.9229
41  50  77.6391  12.9617
42   9  77.5113  12.9801
43  48  77.5978  12.8939
44  50  77.6001  12.9106
45  21  77.5709  12.9020
46  17  77.5617  12.9057
47  19  77.5663  12.9038
48  37  77.5806  13.0104
49   0  77.5053  12.7717
50  12  77.5896  12.8608
51  50  77.6011  12.9023
52  32  77.6374  13.0096
53  16  77.5930  13.0611
54  21  77.5523  12.9299
55  37  77.5726  12.9955
56  50  77.6041  12.9316
57  33  77.5971  13.0068
58  19  77.5732  13.0583
59  18  77.5831  13.0597
60  22  77.5361  13.0134
61   7  77.5566  13.0814
62   5  77.5837  13.1195
63  19  77.6804  12.8311
64   9  77.6809  12.8263
65  44  77.6727  12.8458
66   0  77.0942  13.1791
67  33  77.6765  12.9255

[68 rows x 3 columns]

Naming the columns of the generated dataframe.

In [21]:
dataset3.columns=['Number of Food Outlets','longitude','latitude']
dataset3

    Number of Food Outlets  longitude  latitude
0                       31    77.5944   12.9914
1                       49    77.5937   12.9719
2                       47    77.5648   13.0097
3                        0    76.0303   13.5207
4                        0    74.4891   14.0998
5                       35    77.5714   12.9417
6                        0    76.9627   13.2029
7                       37    77.5491   12.9847
8                        0    76.2752   15.8266
9                        9    77.5474   13.0448
10                       0    73.7291   21.4504
11                      42    77.5789   12.9879
12                      44    77.5625   12.9879
13                       0    77.4484   13.1100
14                      32    77.5489   12.9750
15                      48    77.6025   12.9634
16                      31    77.5952   12.9506
17                       0    76.8024   13.7952
18                      50    77.6079   12.9440
19                      50    77.6153   12.9380
20                      50    77.6227   12.9320
21                       0    77.4920   12.6859
22                      50    77.5885   12.9278
23                      28    77.6487   13.0158
24                      20    77.6226   13.0360
25                      37    77.6044   12.9985
26                      20    77.7164   12.9944
27                      21    77.6869   12.9923
28                       0    76.5761   10.8368
29                      40    77.5609   13.0323
..                     ...        ...       ...
38                      50    77.6209   12.9240
39                      19    77.6299   12.8931
40                      50    77.5798   12.9229
41                      50    77.6391   12.9617
42                       9    77.5113   12.9801
43                      48    77.5978   12.8939
44                      50    77.6001   12.9106
45                      21    77.5709   12.9020
46                      17    77.5617   12.9057
47                      19    77.5663   12.9038
48                      37    77.5806   13.0104
49                       0    77.5053   12.7717
50                      12    77.5896   12.8608
51                      50    77.6011   12.9023
52                      32    77.6374   13.0096
53                      16    77.5930   13.0611
54                      21    77.5523   12.9299
55                      37    77.5726   12.9955
56                      50    77.6041   12.9316
57                      33    77.5971   13.0068
58                      19    77.5732   13.0583
59                      18    77.5831   13.0597
60                      22    77.5361   13.0134
61                       7    77.5566   13.0814
62                       5    77.5837   13.1195
63                      19    77.6804   12.8311
64                       9    77.6809   12.8263
65                      44    77.6727   12.8458
66                       0    77.0942   13.1791
67                      33    77.6765   12.9255

[68 rows x 3 columns]

Printing all datasets.

Printing all three datasets

Dataset1: Consists of data of all areas/neighborhoods in bangalore with their corresponding pincodes and longitudes and latitude.This dataset gives informations regarding the neigborhoods in bangalore.

In [22]:
dataset1

,Country,Pincode,Area,Bangalore-Division,Latitude,Longitude
0,IN,560001,Bangalore G.P.O.,Bangalore North,12.9914,77.5944
1,IN,560001,Legislators Home,Bangalore North,12.9914,77.5944
2,IN,560001,Vasanthanagar,Bangalore North,12.9914,77.5944
3,IN,560001,Mahatma Gandhi Road,Bangalore North,12.9914,77.5944
4,IN,560001,Vidhana Soudha,Bangalore North,12.9914,77.5944
5,IN,560001,Rajbhavan (Bangalore),Bangalore North,12.9914,77.5944
6,IN,560001,HighCourt,Bangalore North,12.9914,77.5944
7,IN,560001,Cubban Road,Bangalore North,12.9914,77.5944
8,IN,560001,Bangalore Bazaar,Bangalore North,12.9914,77.5944
9,IN,560001,CMM Court Complex,Bangalore North,12.9914,77.5944
10,IN,560001,Dr. Ambedkar Veedhi,Bangalore North,12.9914,77.5944
11,IN,560002,Bangalore City,Bangalore North,12.9719,77.5937
12,IN,560002,Bangalore Corporation Building,Bangalore South,12.9719,77.5937
13,IN,560002,Sri Jayachamarajendra Road,Bangalore South,12.9719,77.5937
14,IN,560003,Palace Guttahalli,Bangalore North,13.0097,77.5648
15,IN,560003,Malleswaram,Bangalore North,13.0097,77.5648
16,IN,560003,Swimming Pool Extn,Bangalore North,13.0097,77.5648
17,IN,560003,Vyalikaval Extn,Bangalore North,13.0097,77.5648
18,IN,560004,Pampamahakavi Road,Bangalore South,13.5207,76.0303
19,IN,560004,Thyagarajnagar,Bangalore South,13.5207,76.0303
20,IN,560004,Mavalli,Bangalore South,14.0998,74.4891
21,IN,560004,Basavanagudi,Bangalore South,12.9417,77.5714
22,IN,560005,Fraser Town,Bangalore North,13.2029,76.9627
23,IN,560006,J.C.Nagar,Bangalore North,13.2029,76.9627
24,IN,560006,Training Command IAF,Bangalore North,13.2029,76.9627
25,IN,560007,Agram,Bangalore South,13.2029,76.9627
26,IN,560007,Air Force Hospital,Bangalore North,13.2029,76.9627
27,IN,560008,Hulsur Bazaar,Bangalore North,13.2029,76.9627
28,IN,560008,H.A.L II Stage,Bangalore North,13.2029,76.9627
29,IN,560009,K. G. Road,Bangalore North,13.2029,76.9627
...,...,...,...,...,...,...
203,IN,560087,Gunjur,Bangalore North,12.9316,77.6041
204,IN,560090,Tarabanahalli,Bangalore North,13.0068,77.5971
205,IN,560091,Herohalli,Bangalore North,13.0583,77.5732
206,IN,560091,Bapagrama,Bangalore North,13.0583,77.5732
207,IN,560091,Viswaneedam,Bangalore North,13.0583,77.5732
208,IN,560091,Herohalli,Bangalore north,13.0583,77.5732
209,IN,560092,Amruthahalli,Bangalore North,13.0597,77.5831
210,IN,560092,Byatarayanapura,Bangalore North,13.0611,77.5930
211,IN,560092,Kodigehalli,Bangalore North,13.0583,77.5732
212,IN,560092,Sahakaranagar P.O,Bangalore North,13.0597,77.5831
213,IN,560093,C.V.Raman Nagar,Bangalore North,13.0068,77.5971
214,IN,560094,ISRO Anthariksha Bhavan,Bangalore North,13.0068,77.5971
215,IN,560094,R.M.V. Extension II Stage,Bangalore North,13.0068,77.5971
216,IN,560095,Koramangala VI Bk,Bangalore South,13.0068,77.5971
217,IN,560096,Nandinilayout,Bangalore North,13.0134,77.5361
218,IN,560097,Chikkabettahalli,Bangalore North,13.0814,77.5566
219,IN,560097,Vidyaranyapura,Bangalore North,13.0814,77.5566
220,IN,560098,Rajarajeshwarinagar,Bangalore South,13.1195,77.5837
221,IN,560098,Kenchanahalli,Bangalore South,13.1195,77.5837
222,IN,560099,Bommasandra Industrial Estate,Bangalore South,12.8311,77.6804
223,IN,560099,Hebbagodi,Bangalore South,12.8263,77.6809
224,IN,560099,Muthanallur,Bangalore South,12.8311,77.6804
225,IN,560100,Electronics City,Bangalore South,12.8458,77.6727
226,IN,560100,Wipro Limited,Bangalore South,12.8458,77.6727
227,IN,560102,HSR Layout,Bangalore South,13.1791,77.0942
228,IN,560103,Bellandur,Bangalore South,12.9255,77.6765
229,IN,560103,Panathur,Bangalore South,12.9255,77.6765
230,IN,560104,Hampinagar,Bangalore North,13.1791,77.0942
231,IN,560109,Thalaghattapura,Bangalore South,13.1791,77.0942
232,IN,560110,Ullalu Upanagar,Bangalore North,13.1791,77.0942

Dataset2: Consists of data :number of the companies with various employee sizes ,for ll pincodes in Bangalore. This dataset helps identify the neighborhoods in bangalore(with help of pincode) best suited for opening a restaurant.Potential neighborhoods will be the ones with high number of employees.

In [23]:
dataset2

,Pincode,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,560001,157,90,91,54,22,14,8,7
1,560002,47,23,13,6,0,2,0,1
2,560003,54,22,16,5,2,1,0,0
3,560004,53,28,27,10,0,2,1,1
4,560005,37,14,6,0,1,0,1,1
5,560006,1,1,1,1,0,0,0,0
6,560007,0,0,0,0,0,0,0,0
7,560008,101,57,38,16,2,3,0,0
8,560009,30,13,14,2,1,0,0,0
9,560010,64,31,19,6,6,0,0,1
10,560011,62,38,22,7,4,0,0,0
11,560012,3,0,0,2,0,1,0,0
12,560013,7,5,7,1,0,0,0,1
13,560014,2,0,0,0,0,0,0,0
14,560015,6,1,1,0,0,0,0,0
15,560016,20,15,6,5,1,1,0,1
16,560017,36,15,16,7,0,3,0,1
17,560018,13,7,8,3,0,0,0,0
18,560019,6,2,4,1,0,0,0,1
19,560020,33,15,8,5,3,0,0,1
20,560021,19,1,1,0,0,0,0,0
21,560022,30,23,17,10,2,5,0,1
22,560023,3,7,1,2,0,0,0,0
23,560024,16,14,11,5,0,2,1,0
24,560025,93,47,50,16,14,6,1,3
25,560026,21,12,6,3,0,0,0,0
26,560027,38,30,36,9,7,1,1,2
27,560029,28,15,17,6,7,4,3,2
28,560030,13,11,4,0,0,0,0,2
29,560032,0,23,9,3,1,0,1,0
...,...,...,...,...,...,...,...,...,...
67,560073,2,6,2,0,0,2,0,0
68,560074,6,7,11,0,2,0,0,0
69,560075,38,14,8,2,0,2,0,0
70,560076,72,35,26,10,6,3,2,5
71,560077,12,5,7,2,0,0,0,0
72,560078,100,53,43,14,8,1,0,0
73,560079,45,14,10,2,0,0,0,0
74,560080,22,16,13,3,1,2,0,0
75,560082,16,15,11,4,0,0,0,0
76,560083,8,4,5,1,0,0,0,0
77,560084,20,5,2,0,0,0,0,0
78,560085,34,13,13,2,0,0,0,0
79,560086,18,10,10,2,1,1,0,1
80,560087,4,2,2,2,2,3,0,0
81,560090,7,5,1,0,0,0,0,0
82,560091,38,8,15,1,0,0,0,0
83,560092,21,14,9,5,0,1,0,1
84,560093,19,5,7,9,5,0,1,0
85,560094,29,18,7,4,3,0,0,1
86,560095,67,44,36,14,2,0,2,2
87,560096,8,1,7,0,0,0,0,0
88,560097,16,3,5,1,1,0,0,0
89,560098,16,6,5,0,1,0,0,0
90,560099,24,22,40,11,7,3,2,0
91,560100,48,38,35,23,6,6,2,5
92,560102,98,64,46,11,5,0,0,1
93,560103,22,28,27,21,7,2,5,7
94,560104,5,0,2,1,0,0,0,0
95,560109,0,0,0,0,0,0,0,0
96,560110,1,0,0,0,0,0,0,0

Dataset 3:Consists of all longitudes and latitudes (same for many pincodes), along with the number of food outlets within 2000m (2km). This data will help select a potential areas/neighborhood to open a restaurant.Potential area/neighbourhoods wll be ones with low number of food outlets.

In [24]:
dataset3

    Number of Food Outlets  longitude  latitude
0                       31    77.5944   12.9914
1                       49    77.5937   12.9719
2                       47    77.5648   13.0097
3                        0    76.0303   13.5207
4                        0    74.4891   14.0998
5                       35    77.5714   12.9417
6                        0    76.9627   13.2029
7                       37    77.5491   12.9847
8                        0    76.2752   15.8266
9                        9    77.5474   13.0448
10                       0    73.7291   21.4504
11                      42    77.5789   12.9879
12                      44    77.5625   12.9879
13                       0    77.4484   13.1100
14                      32    77.5489   12.9750
15                      48    77.6025   12.9634
16                      31    77.5952   12.9506
17                       0    76.8024   13.7952
18                      50    77.6079   12.9440
19                      50    77.6153   12.9380
20                      50    77.6227   12.9320
21                       0    77.4920   12.6859
22                      50    77.5885   12.9278
23                      28    77.6487   13.0158
24                      20    77.6226   13.0360
25                      37    77.6044   12.9985
26                      20    77.7164   12.9944
27                      21    77.6869   12.9923
28                       0    76.5761   10.8368
29                      40    77.5609   13.0323
..                     ...        ...       ...
38                      50    77.6209   12.9240
39                      19    77.6299   12.8931
40                      50    77.5798   12.9229
41                      50    77.6391   12.9617
42                       9    77.5113   12.9801
43                      48    77.5978   12.8939
44                      50    77.6001   12.9106
45                      21    77.5709   12.9020
46                      17    77.5617   12.9057
47                      19    77.5663   12.9038
48                      37    77.5806   13.0104
49                       0    77.5053   12.7717
50                      12    77.5896   12.8608
51                      50    77.6011   12.9023
52                      32    77.6374   13.0096
53                      16    77.5930   13.0611
54                      21    77.5523   12.9299
55                      37    77.5726   12.9955
56                      50    77.6041   12.9316
57                      33    77.5971   13.0068
58                      19    77.5732   13.0583
59                      18    77.5831   13.0597
60                      22    77.5361   13.0134
61                       7    77.5566   13.0814
62                       5    77.5837   13.1195
63                      19    77.6804   12.8311
64                       9    77.6809   12.8263
65                      44    77.6727   12.8458
66                       0    77.0942   13.1791
67                      33    77.6765   12.9255

[68 rows x 3 columns]

Note: All datasets will have the same number of rows and columns during execution of clustering.
    They have different number of rows and columns now, as they have many repeated data in them.

3.Methodology and Results

3.1 Integration of three datasets

In [25]:

body = client_3fa636d9b3f646ac8f3bb5de175890e6.get_object(Bucket='businessproblemibmapplieddatascie-donotdelete-pr-dtdt3j8tjafjfu',Key='Dataset2.xlsx')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_excel(body)
df_data_2.head()

,Pincode,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,560001,157,90,91,54,22,14,8,7
1,560002,47,23,13,6,0,2,0,1
2,560003,54,22,16,5,2,1,0,0
3,560004,53,28,27,10,0,2,1,1
4,560005,37,14,6,0,1,0,1,1

3.1.1 Preparing dataconcat12grouped:merging dataset1 and dataset2 and then obtaining a dataset with the number of companies by Longitude,Latitude and Pincode.

In [26]:
dataset1['Longitude']=dataset1['Longitude'].astype(str)
dataset1['Latitude']=dataset1['Latitude'].astype(str)
dataset1

,Country,Pincode,Area,Bangalore-Division,Latitude,Longitude
0,IN,560001,Bangalore G.P.O.,Bangalore North,12.9914,77.5944
1,IN,560001,Legislators Home,Bangalore North,12.9914,77.5944
2,IN,560001,Vasanthanagar,Bangalore North,12.9914,77.5944
3,IN,560001,Mahatma Gandhi Road,Bangalore North,12.9914,77.5944
4,IN,560001,Vidhana Soudha,Bangalore North,12.9914,77.5944
5,IN,560001,Rajbhavan (Bangalore),Bangalore North,12.9914,77.5944
6,IN,560001,HighCourt,Bangalore North,12.9914,77.5944
7,IN,560001,Cubban Road,Bangalore North,12.9914,77.5944
8,IN,560001,Bangalore Bazaar,Bangalore North,12.9914,77.5944
9,IN,560001,CMM Court Complex,Bangalore North,12.9914,77.5944
10,IN,560001,Dr. Ambedkar Veedhi,Bangalore North,12.9914,77.5944
11,IN,560002,Bangalore City,Bangalore North,12.9719,77.5937
12,IN,560002,Bangalore Corporation Building,Bangalore South,12.9719,77.5937
13,IN,560002,Sri Jayachamarajendra Road,Bangalore South,12.9719,77.5937
14,IN,560003,Palace Guttahalli,Bangalore North,13.0097,77.5648
15,IN,560003,Malleswaram,Bangalore North,13.0097,77.5648
16,IN,560003,Swimming Pool Extn,Bangalore North,13.0097,77.5648
17,IN,560003,Vyalikaval Extn,Bangalore North,13.0097,77.5648
18,IN,560004,Pampamahakavi Road,Bangalore South,13.5207,76.0303
19,IN,560004,Thyagarajnagar,Bangalore South,13.5207,76.0303
20,IN,560004,Mavalli,Bangalore South,14.0998,74.4891
21,IN,560004,Basavanagudi,Bangalore South,12.9417,77.5714
22,IN,560005,Fraser Town,Bangalore North,13.2029,76.9627
23,IN,560006,J.C.Nagar,Bangalore North,13.2029,76.9627
24,IN,560006,Training Command IAF,Bangalore North,13.2029,76.9627
25,IN,560007,Agram,Bangalore South,13.2029,76.9627
26,IN,560007,Air Force Hospital,Bangalore North,13.2029,76.9627
27,IN,560008,Hulsur Bazaar,Bangalore North,13.2029,76.9627
28,IN,560008,H.A.L II Stage,Bangalore North,13.2029,76.9627
29,IN,560009,K. G. Road,Bangalore North,13.2029,76.9627
...,...,...,...,...,...,...
203,IN,560087,Gunjur,Bangalore North,12.9316,77.6041
204,IN,560090,Tarabanahalli,Bangalore North,13.0068,77.5971
205,IN,560091,Herohalli,Bangalore North,13.0583,77.5732
206,IN,560091,Bapagrama,Bangalore North,13.0583,77.5732
207,IN,560091,Viswaneedam,Bangalore North,13.0583,77.5732
208,IN,560091,Herohalli,Bangalore north,13.0583,77.5732
209,IN,560092,Amruthahalli,Bangalore North,13.0597,77.5831
210,IN,560092,Byatarayanapura,Bangalore North,13.0611,77.593
211,IN,560092,Kodigehalli,Bangalore North,13.0583,77.5732
212,IN,560092,Sahakaranagar P.O,Bangalore North,13.0597,77.5831
213,IN,560093,C.V.Raman Nagar,Bangalore North,13.0068,77.5971
214,IN,560094,ISRO Anthariksha Bhavan,Bangalore North,13.0068,77.5971
215,IN,560094,R.M.V. Extension II Stage,Bangalore North,13.0068,77.5971
216,IN,560095,Koramangala VI Bk,Bangalore South,13.0068,77.5971
217,IN,560096,Nandinilayout,Bangalore North,13.0134,77.5361
218,IN,560097,Chikkabettahalli,Bangalore North,13.0814,77.5566
219,IN,560097,Vidyaranyapura,Bangalore North,13.0814,77.5566
220,IN,560098,Rajarajeshwarinagar,Bangalore South,13.1195,77.5837
221,IN,560098,Kenchanahalli,Bangalore South,13.1195,77.5837
222,IN,560099,Bommasandra Industrial Estate,Bangalore South,12.8311,77.6804
223,IN,560099,Hebbagodi,Bangalore South,12.8263,77.6809
224,IN,560099,Muthanallur,Bangalore South,12.8311,77.6804
225,IN,560100,Electronics City,Bangalore South,12.8458,77.6727
226,IN,560100,Wipro Limited,Bangalore South,12.8458,77.6727
227,IN,560102,HSR Layout,Bangalore South,13.1791,77.0942
228,IN,560103,Bellandur,Bangalore South,12.9255,77.6765
229,IN,560103,Panathur,Bangalore South,12.9255,77.6765
230,IN,560104,Hampinagar,Bangalore North,13.1791,77.0942
231,IN,560109,Thalaghattapura,Bangalore South,13.1791,77.0942
232,IN,560110,Ullalu Upanagar,Bangalore North,13.1791,77.0942

In [27]:
dataf=dataset1.groupby(['Pincode'], sort=False).agg(','.join)
dataf1=dataf.drop(['Country','Bangalore-Division'], axis=1)
dataf1

,Area,Latitude,Longitude
Pincode,,,
560001,"Bangalore G.P.O.,Legislators Home,Vasanthanaga...","12.9914,12.9914,12.9914,12.9914,12.9914,12.991...","77.5944,77.5944,77.5944,77.5944,77.5944,77.594..."
560002,"Bangalore City,Bangalore Corporation Building,...","12.9719,12.9719,12.9719","77.5937,77.5937,77.5937"
560003,"Palace Guttahalli,Malleswaram,Swimming Pool Ex...","13.0097,13.0097,13.0097,13.0097","77.5648,77.5648,77.5648,77.5648"
560004,"Pampamahakavi Road,Thyagarajnagar,Mavalli,Basa...","13.5207,13.5207,14.0998,12.9417","76.0303,76.0303,74.4891,77.5714"
560005,Fraser Town,13.2029,76.9627
560006,"J.C.Nagar,Training Command IAF","13.2029,13.2029","76.9627,76.9627"
560007,"Agram,Air Force Hospital","13.2029,13.2029","76.9627,76.9627"
560008,"Hulsur Bazaar,H.A.L II Stage","13.2029,13.2029","76.9627,76.9627"
560009,"K. G. Road,Bangalore Dist Offices Bldg","13.2029,13.2029","76.9627,76.9627"
560010,"Rajajinagar,Industrial Estate (Bangalore),Raja...","12.9847,12.9847,12.9847","77.5491,77.5491,77.5491"
560011,"Jayangar III Block,Madhavan Park","15.8266,15.8266","76.2752,76.2752"
560012,Science Institute,15.8266,76.2752
560013,Jalahalli,13.0448,77.5474
560014,Jalahalli East,15.8266,76.2752
560015,Jalahalli West,15.8266,76.2752
560016,"Krishnarajapuram R S,Doorvaninagar,Ramamurthy ...","15.8266,15.8266,15.8266","76.2752,76.2752,76.2752"
560017,"Vimanapura,NAL","21.4504,21.4504","73.7291,73.7291"
560018,Chamrajpet (Bangalore),15.8266,76.2752
560019,Gaviopuram Extension,15.8266,76.2752
560020,Seshadripuram,12.9879,77.5789
560021,"Gayathrinagar,Srirampuram","12.9879,12.9879","77.5625,77.5625"
560022,"Yeshwanthpur Bazar,Yeswanthpura","13.11,13.11","77.4484,77.4484"
560023,Magadi Road,12.975,77.5489
560024,"Anandnagar (Bangalore),Hebbal Kempapura,H.A. Farm","13.11,13.11,13.11","77.4484,77.4484,77.4484"
560025,"Museum Road,Richmond Town,CMP Centre And School","12.9634,12.9634,12.9634","77.6025,77.6025,77.6025"
560026,"Deepanjalinagar,Governmemnt Electric Factory","13.11,13.11","77.4484,77.4484"
560027,"Sampangiramnagar,Wilson Garden,Shanthinagar","12.9506,12.9506,12.9506","77.5952,77.5952,77.5952"
560029,"Tavarekere,Dharmaram College","13.7952,13.7952","76.8024,76.8024"
560030,Adugodi,12.944,77.6079
560032,"R T Nagar,Kanakanagar,P&T Col. Kavalbyrasandra","12.938,12.938,12.938","77.6153,77.6153,77.6153"
...,...,...,...
560073,"Nagasandra ,Nelakadiranahalli,Bagalgunte,Chikk...","12.9229,12.9229,12.9229,12.9229","77.5798,77.5798,77.5798,77.5798"
560074,"Kumbalagodu,Ramohalli,Kumbalgodu Gollahalli","12.9229,12.9229,12.9229","77.5798,77.5798,77.5798"
560075,"Jeevanbhimanagar,New Thippasandra,Jeevabhimanagar","12.9229,12.9229,12.9229","77.5798,77.5798,77.5798"
560076,"Bannerghatta Road,Mico Layout,Mount St Joseph,...","12.8939,12.9106,12.8939,12.8939,12.8939","77.5978,77.6001,77.5978,77.5978,77.5978"
560077,"Kothanur,Dr. Shivarama Karanth Nagar,Doddagubbi","12.9229,12.9229,12.9229","77.5798,77.5798,77.5798"
560078,"Yelachenahalli,Kumaraswamy Layout,J P Nagar,JP...","12.902,12.9057,12.9038,12.9038","77.5709,77.5617,77.5663,77.5663"
560079,"Kamakshipalya,K H B Colony,Basaveshwaranagar","12.9229,12.9229,12.9229","77.5798,77.5798,77.5798"
560080,Sadashivanagar,13.0104,77.5806
560082,Bolare,12.7717,77.5053
560083,"Gottigere,Bannerghatta","12.8608,12.9023","77.5896,77.6011"
560084,"Lingarajapuram,Kacharakanahalli,St. Thomas Town","13.0096,13.0096,13.0096","77.6374,77.6374,77.6374"
560085,"Byatarayanapura,Kathriguppe,Girinagar (Bangalo...","13.0611,12.9299,12.9955,12.9955,12.9955","77.593,77.5523,77.5726,77.5726,77.5726"
560086,"West of Chord Road II stage,Mahalakshmipuram L...","12.9316,12.9316","77.6041,77.6041"
560087,"Vartur,Muthusandra,Gunjur","12.9316,12.9316,12.9316","77.6041,77.6041,77.6041"
560090,Tarabanahalli,13.0068,77.5971
560091,"Herohalli,Bapagrama,Viswaneedam,Herohalli","13.0583,13.0583,13.0583,13.0583","77.5732,77.5732,77.5732,77.5732"
560092,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak...","13.0597,13.0611,13.0583,13.0597","77.5831,77.593,77.5732,77.5831"
560093,C.V.Raman Nagar,13.0068,77.5971
560094,"ISRO Anthariksha Bhavan,R.M.V. Extension II Stage","13.0068,13.0068","77.5971,77.5971"
560095,Koramangala VI Bk,13.0068,77.5971
560096,Nandinilayout,13.0134,77.5361
560097,"Chikkabettahalli,Vidyaranyapura","13.0814,13.0814","77.5566,77.5566"
560098,"Rajarajeshwarinagar,Kenchanahalli","13.1195,13.1195","77.5837,77.5837"
560099,"Bommasandra Industrial Estate,Hebbagodi,Muthan...","12.8311,12.8263,12.8311","77.6804,77.6809,77.6804"
560100,"Electronics City,Wipro Limited","12.8458,12.8458","77.6727,77.6727"
560102,HSR Layout,13.1791,77.0942
560103,"Bellandur,Panathur","12.9255,12.9255","77.6765,77.6765"
560104,Hampinagar,13.1791,77.0942
560109,Thalaghattapura,13.1791,77.0942
560110,Ullalu Upanagar,13.1791,77.0942

In [28]:
dataf2=dataf1.applymap(lambda x: x if ',' not in str(x) else ','.join(sorted(set(y.strip() for y in(x.split(','))))))
dataf3=dataf2.reset_index(drop=False, inplace=False)
dataf3

,Pincode,Area,Latitude,Longitude
0,560001,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co...",12.9914,77.5944
1,560002,"Bangalore City,Bangalore Corporation Building,...",12.9719,77.5937
2,560003,"Malleswaram,Palace Guttahalli,Swimming Pool Ex...",13.0097,77.5648
3,560004,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga...","12.9417,13.5207,14.0998","74.4891,76.0303,77.5714"
4,560005,Fraser Town,13.2029,76.9627
5,560006,"J.C.Nagar,Training Command IAF",13.2029,76.9627
6,560007,"Agram,Air Force Hospital",13.2029,76.9627
7,560008,"H.A.L II Stage,Hulsur Bazaar",13.2029,76.9627
8,560009,"Bangalore Dist Offices Bldg,K. G. Road",13.2029,76.9627
9,560010,"Industrial Estate (Bangalore),Rajajinagar,Raja...",12.9847,77.5491
10,560011,"Jayangar III Block,Madhavan Park",15.8266,76.2752
11,560012,Science Institute,15.8266,76.2752
12,560013,Jalahalli,13.0448,77.5474
13,560014,Jalahalli East,15.8266,76.2752
14,560015,Jalahalli West,15.8266,76.2752
15,560016,"Doorvaninagar,Krishnarajapuram R S,Ramamurthy ...",15.8266,76.2752
16,560017,"NAL,Vimanapura",21.4504,73.7291
17,560018,Chamrajpet (Bangalore),15.8266,76.2752
18,560019,Gaviopuram Extension,15.8266,76.2752
19,560020,Seshadripuram,12.9879,77.5789
20,560021,"Gayathrinagar,Srirampuram",12.9879,77.5625
21,560022,"Yeshwanthpur Bazar,Yeswanthpura",13.11,77.4484
22,560023,Magadi Road,12.975,77.5489
23,560024,"Anandnagar (Bangalore),H.A. Farm,Hebbal Kempapura",13.11,77.4484
24,560025,"CMP Centre And School,Museum Road,Richmond Town",12.9634,77.6025
25,560026,"Deepanjalinagar,Governmemnt Electric Factory",13.11,77.4484
26,560027,"Sampangiramnagar,Shanthinagar,Wilson Garden",12.9506,77.5952
27,560029,"Dharmaram College,Tavarekere",13.7952,76.8024
28,560030,Adugodi,12.944,77.6079
29,560032,"Kanakanagar,P&T Col. Kavalbyrasandra,R T Nagar",12.938,77.6153
...,...,...,...,...
67,560073,"Bagalgunte,Chikkabidarkal,Nagasandra,Nelakadir...",12.9229,77.5798
68,560074,"Kumbalagodu,Kumbalgodu Gollahalli,Ramohalli",12.9229,77.5798
69,560075,"Jeevabhimanagar,Jeevanbhimanagar,New Thippasandra",12.9229,77.5798
70,560076,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph...","12.8939,12.9106","77.5978,77.6001"
71,560077,"Doddagubbi,Dr. Shivarama Karanth Nagar,Kothanur",12.9229,77.5798
72,560078,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou...","12.902,12.9038,12.9057","77.5617,77.5663,77.5709"
73,560079,"Basaveshwaranagar,K H B Colony,Kamakshipalya",12.9229,77.5798
74,560080,Sadashivanagar,13.0104,77.5806
75,560082,Bolare,12.7717,77.5053
76,560083,"Bannerghatta,Gottigere","12.8608,12.9023","77.5896,77.6011"
77,560084,"Kacharakanahalli,Lingarajapuram,St. Thomas Town",13.0096,77.6374
78,560085,"Banashankari III Stage,Byatarayanapura,Girinag...","12.9299,12.9955,13.0611","77.5523,77.5726,77.593"
79,560086,"Mahalakshmipuram Layout,West of Chord Road II ...",12.9316,77.6041
80,560087,"Gunjur,Muthusandra,Vartur",12.9316,77.6041
81,560090,Tarabanahalli,13.0068,77.5971
82,560091,"Bapagrama,Herohalli,Viswaneedam",13.0583,77.5732
83,560092,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak...","13.0583,13.0597,13.0611","77.5732,77.5831,77.593"
84,560093,C.V.Raman Nagar,13.0068,77.5971
85,560094,"ISRO Anthariksha Bhavan,R.M.V. Extension II Stage",13.0068,77.5971
86,560095,Koramangala VI Bk,13.0068,77.5971
87,560096,Nandinilayout,13.0134,77.5361
88,560097,"Chikkabettahalli,Vidyaranyapura",13.0814,77.5566
89,560098,"Kenchanahalli,Rajarajeshwarinagar",13.1195,77.5837
90,560099,"Bommasandra Industrial Estate,Hebbagodi,Muthan...","12.8263,12.8311","77.6804,77.6809"
91,560100,"Electronics City,Wipro Limited",12.8458,77.6727
92,560102,HSR Layout,13.1791,77.0942
93,560103,"Bellandur,Panathur",12.9255,77.6765
94,560104,Hampinagar,13.1791,77.0942
95,560109,Thalaghattapura,13.1791,77.0942
96,560110,Ullalu Upanagar,13.1791,77.0942

In [29]:
df_data_2=dataset2.drop(['Pincode'], axis=1)
df_data_2

,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,157,90,91,54,22,14,8,7
1,47,23,13,6,0,2,0,1
2,54,22,16,5,2,1,0,0
3,53,28,27,10,0,2,1,1
4,37,14,6,0,1,0,1,1
5,1,1,1,1,0,0,0,0
6,0,0,0,0,0,0,0,0
7,101,57,38,16,2,3,0,0
8,30,13,14,2,1,0,0,0
9,64,31,19,6,6,0,0,1
10,62,38,22,7,4,0,0,0
11,3,0,0,2,0,1,0,0
12,7,5,7,1,0,0,0,1
13,2,0,0,0,0,0,0,0
14,6,1,1,0,0,0,0,0
15,20,15,6,5,1,1,0,1
16,36,15,16,7,0,3,0,1
17,13,7,8,3,0,0,0,0
18,6,2,4,1,0,0,0,1
19,33,15,8,5,3,0,0,1
20,19,1,1,0,0,0,0,0
21,30,23,17,10,2,5,0,1
22,3,7,1,2,0,0,0,0
23,16,14,11,5,0,2,1,0
24,93,47,50,16,14,6,1,3
25,21,12,6,3,0,0,0,0
26,38,30,36,9,7,1,1,2
27,28,15,17,6,7,4,3,2
28,13,11,4,0,0,0,0,2
29,0,23,9,3,1,0,1,0
...,...,...,...,...,...,...,...,...
67,2,6,2,0,0,2,0,0
68,6,7,11,0,2,0,0,0
69,38,14,8,2,0,2,0,0
70,72,35,26,10,6,3,2,5
71,12,5,7,2,0,0,0,0
72,100,53,43,14,8,1,0,0
73,45,14,10,2,0,0,0,0
74,22,16,13,3,1,2,0,0
75,16,15,11,4,0,0,0,0
76,8,4,5,1,0,0,0,0
77,20,5,2,0,0,0,0,0
78,34,13,13,2,0,0,0,0
79,18,10,10,2,1,1,0,1
80,4,2,2,2,2,3,0,0
81,7,5,1,0,0,0,0,0
82,38,8,15,1,0,0,0,0
83,21,14,9,5,0,1,0,1
84,19,5,7,9,5,0,1,0
85,29,18,7,4,3,0,0,1
86,67,44,36,14,2,0,2,2
87,8,1,7,0,0,0,0,0
88,16,3,5,1,1,0,0,0
89,16,6,5,0,1,0,0,0
90,24,22,40,11,7,3,2,0
91,48,38,35,23,6,6,2,5
92,98,64,46,11,5,0,0,1
93,22,28,27,21,7,2,5,7
94,5,0,2,1,0,0,0,0
95,0,0,0,0,0,0,0,0
96,1,0,0,0,0,0,0,0

attaching dataset2 (designated as df_data_2 in the previous step) to dataf3 (dataset1 - grouped by Pincode)

In [30]:
dataconcat12=pd.concat([dataf3,df_data_2], axis=1)
dataconcat12

,Pincode,Area,Latitude,Longitude,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,560001,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co...",12.9914,77.5944,157,90,91,54,22,14,8,7
1,560002,"Bangalore City,Bangalore Corporation Building,...",12.9719,77.5937,47,23,13,6,0,2,0,1
2,560003,"Malleswaram,Palace Guttahalli,Swimming Pool Ex...",13.0097,77.5648,54,22,16,5,2,1,0,0
3,560004,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga...","12.9417,13.5207,14.0998","74.4891,76.0303,77.5714",53,28,27,10,0,2,1,1
4,560005,Fraser Town,13.2029,76.9627,37,14,6,0,1,0,1,1
5,560006,"J.C.Nagar,Training Command IAF",13.2029,76.9627,1,1,1,1,0,0,0,0
6,560007,"Agram,Air Force Hospital",13.2029,76.9627,0,0,0,0,0,0,0,0
7,560008,"H.A.L II Stage,Hulsur Bazaar",13.2029,76.9627,101,57,38,16,2,3,0,0
8,560009,"Bangalore Dist Offices Bldg,K. G. Road",13.2029,76.9627,30,13,14,2,1,0,0,0
9,560010,"Industrial Estate (Bangalore),Rajajinagar,Raja...",12.9847,77.5491,64,31,19,6,6,0,0,1
10,560011,"Jayangar III Block,Madhavan Park",15.8266,76.2752,62,38,22,7,4,0,0,0
11,560012,Science Institute,15.8266,76.2752,3,0,0,2,0,1,0,0
12,560013,Jalahalli,13.0448,77.5474,7,5,7,1,0,0,0,1
13,560014,Jalahalli East,15.8266,76.2752,2,0,0,0,0,0,0,0
14,560015,Jalahalli West,15.8266,76.2752,6,1,1,0,0,0,0,0
15,560016,"Doorvaninagar,Krishnarajapuram R S,Ramamurthy ...",15.8266,76.2752,20,15,6,5,1,1,0,1
16,560017,"NAL,Vimanapura",21.4504,73.7291,36,15,16,7,0,3,0,1
17,560018,Chamrajpet (Bangalore),15.8266,76.2752,13,7,8,3,0,0,0,0
18,560019,Gaviopuram Extension,15.8266,76.2752,6,2,4,1,0,0,0,1
19,560020,Seshadripuram,12.9879,77.5789,33,15,8,5,3,0,0,1
20,560021,"Gayathrinagar,Srirampuram",12.9879,77.5625,19,1,1,0,0,0,0,0
21,560022,"Yeshwanthpur Bazar,Yeswanthpura",13.11,77.4484,30,23,17,10,2,5,0,1
22,560023,Magadi Road,12.975,77.5489,3,7,1,2,0,0,0,0
23,560024,"Anandnagar (Bangalore),H.A. Farm,Hebbal Kempapura",13.11,77.4484,16,14,11,5,0,2,1,0
24,560025,"CMP Centre And School,Museum Road,Richmond Town",12.9634,77.6025,93,47,50,16,14,6,1,3
25,560026,"Deepanjalinagar,Governmemnt Electric Factory",13.11,77.4484,21,12,6,3,0,0,0,0
26,560027,"Sampangiramnagar,Shanthinagar,Wilson Garden",12.9506,77.5952,38,30,36,9,7,1,1,2
27,560029,"Dharmaram College,Tavarekere",13.7952,76.8024,28,15,17,6,7,4,3,2
28,560030,Adugodi,12.944,77.6079,13,11,4,0,0,0,0,2
29,560032,"Kanakanagar,P&T Col. Kavalbyrasandra,R T Nagar",12.938,77.6153,0,23,9,3,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
67,560073,"Bagalgunte,Chikkabidarkal,Nagasandra,Nelakadir...",12.9229,77.5798,2,6,2,0,0,2,0,0
68,560074,"Kumbalagodu,Kumbalgodu Gollahalli,Ramohalli",12.9229,77.5798,6,7,11,0,2,0,0,0
69,560075,"Jeevabhimanagar,Jeevanbhimanagar,New Thippasandra",12.9229,77.5798,38,14,8,2,0,2,0,0
70,560076,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph...","12.8939,12.9106","77.5978,77.6001",72,35,26,10,6,3,2,5
71,560077,"Doddagubbi,Dr. Shivarama Karanth Nagar,Kothanur",12.9229,77.5798,12,5,7,2,0,0,0,0
72,560078,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou...","12.902,12.9038,12.9057","77.5617,77.5663,77.5709",100,53,43,14,8,1,0,0
73,560079,"Basaveshwaranagar,K H B Colony,Kamakshipalya",12.9229,77.5798,45,14,10,2,0,0,0,0
74,560080,Sadashivanagar,13.0104,77.5806,22,16,13,3,1,2,0,0
75,560082,Bolare,12.7717,77.5053,16,15,11,4,0,0,0,0
76,560083,"Bannerghatta,Gottigere","12.8608,12.9023","77.5896,77.6011",8,4,5,1,0,0,0,0
77,560084,"Kacharakanahalli,Lingarajapuram,St. Thomas Town",13.0096,77.6374,20,5,2,0,0,0,0,0
78,560085,"Banashankari III Stage,Byatarayanapura,Girinag...","12.9299,12.9955,13.0611","77.5523,77.5726,77.593",34,13,13,2,0,0,0,0
79,560086,"Mahalakshmipuram Layout,West of Chord Road II ...",12.9316,77.6041,18,10,10,2,1,1,0,1
80,560087,"Gunjur,Muthusandra,Vartur",12.9316,77.6041,4,2,2,2,2,3,0,0
81,560090,Tarabanahalli,13.0068,77.5971,7,5,1,0,0,0,0,0
82,560091,"Bapagrama,Herohalli,Viswaneedam",13.0583,77.5732,38,8,15,1,0,0,0,0
83,560092,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak...","13.0583,13.0597,13.0611","77.5732,77.5831,77.593",21,14,9,5,0,1,0,1
84,560093,C.V.Raman Nagar,13.0068,77.5971,19,5,7,9,5,0,1,0
85,560094,"ISRO Anthariksha Bhavan,R.M.V. Extension II Stage",13.0068,77.5971,29,18,7,4,3,0,0,1
86,560095,Koramangala VI Bk,13.0068,77.5971,67,44,36,14,2,0,2,2
87,560096,Nandinilayout,13.0134,77.5361,8,1,7,0,0,0,0,0
88,560097,"Chikkabettahalli,Vidyaranyapura",13.0814,77.5566,16,3,5,1,1,0,0,0
89,560098,"Kenchanahalli,Rajarajeshwarinagar",13.1195,77.5837,16,6,5,0,1,0,0,0
90,560099,"Bommasandra Industrial Estate,Hebbagodi,Muthan...","12.8263,12.8311","77.6804,77.6809",24,22,40,11,7,3,2,0
91,560100,"Electronics City,Wipro Limited",12.8458,77.6727,48,38,35,23,6,6,2,5
92,560102,HSR Layout,13.1791,77.0942,98,64,46,11,5,0,0,1
93,560103,"Bellandur,Panathur",12.9255,77.6765,22,28,27,21,7,2,5,7
94,560104,Hampinagar,13.1791,77.0942,5,0,2,1,0,0,0,0
95,560109,Thalaghattapura,13.1791,77.0942,0,0,0,0,0,0,0,0
96,560110,Ullalu Upanagar,13.1791,77.0942,1,0,0,0,0,0,0,0

In [31]:
dataconcat12['Pincode']=dataconcat12['Pincode'].astype(str)
dataconcat12['Area']=dataconcat12['Area'].astype(str)
dataconcat12

,Pincode,Area,Latitude,Longitude,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,560001,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co...",12.9914,77.5944,157,90,91,54,22,14,8,7
1,560002,"Bangalore City,Bangalore Corporation Building,...",12.9719,77.5937,47,23,13,6,0,2,0,1
2,560003,"Malleswaram,Palace Guttahalli,Swimming Pool Ex...",13.0097,77.5648,54,22,16,5,2,1,0,0
3,560004,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga...","12.9417,13.5207,14.0998","74.4891,76.0303,77.5714",53,28,27,10,0,2,1,1
4,560005,Fraser Town,13.2029,76.9627,37,14,6,0,1,0,1,1
5,560006,"J.C.Nagar,Training Command IAF",13.2029,76.9627,1,1,1,1,0,0,0,0
6,560007,"Agram,Air Force Hospital",13.2029,76.9627,0,0,0,0,0,0,0,0
7,560008,"H.A.L II Stage,Hulsur Bazaar",13.2029,76.9627,101,57,38,16,2,3,0,0
8,560009,"Bangalore Dist Offices Bldg,K. G. Road",13.2029,76.9627,30,13,14,2,1,0,0,0
9,560010,"Industrial Estate (Bangalore),Rajajinagar,Raja...",12.9847,77.5491,64,31,19,6,6,0,0,1
10,560011,"Jayangar III Block,Madhavan Park",15.8266,76.2752,62,38,22,7,4,0,0,0
11,560012,Science Institute,15.8266,76.2752,3,0,0,2,0,1,0,0
12,560013,Jalahalli,13.0448,77.5474,7,5,7,1,0,0,0,1
13,560014,Jalahalli East,15.8266,76.2752,2,0,0,0,0,0,0,0
14,560015,Jalahalli West,15.8266,76.2752,6,1,1,0,0,0,0,0
15,560016,"Doorvaninagar,Krishnarajapuram R S,Ramamurthy ...",15.8266,76.2752,20,15,6,5,1,1,0,1
16,560017,"NAL,Vimanapura",21.4504,73.7291,36,15,16,7,0,3,0,1
17,560018,Chamrajpet (Bangalore),15.8266,76.2752,13,7,8,3,0,0,0,0
18,560019,Gaviopuram Extension,15.8266,76.2752,6,2,4,1,0,0,0,1
19,560020,Seshadripuram,12.9879,77.5789,33,15,8,5,3,0,0,1
20,560021,"Gayathrinagar,Srirampuram",12.9879,77.5625,19,1,1,0,0,0,0,0
21,560022,"Yeshwanthpur Bazar,Yeswanthpura",13.11,77.4484,30,23,17,10,2,5,0,1
22,560023,Magadi Road,12.975,77.5489,3,7,1,2,0,0,0,0
23,560024,"Anandnagar (Bangalore),H.A. Farm,Hebbal Kempapura",13.11,77.4484,16,14,11,5,0,2,1,0
24,560025,"CMP Centre And School,Museum Road,Richmond Town",12.9634,77.6025,93,47,50,16,14,6,1,3
25,560026,"Deepanjalinagar,Governmemnt Electric Factory",13.11,77.4484,21,12,6,3,0,0,0,0
26,560027,"Sampangiramnagar,Shanthinagar,Wilson Garden",12.9506,77.5952,38,30,36,9,7,1,1,2
27,560029,"Dharmaram College,Tavarekere",13.7952,76.8024,28,15,17,6,7,4,3,2
28,560030,Adugodi,12.944,77.6079,13,11,4,0,0,0,0,2
29,560032,"Kanakanagar,P&T Col. Kavalbyrasandra,R T Nagar",12.938,77.6153,0,23,9,3,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
67,560073,"Bagalgunte,Chikkabidarkal,Nagasandra,Nelakadir...",12.9229,77.5798,2,6,2,0,0,2,0,0
68,560074,"Kumbalagodu,Kumbalgodu Gollahalli,Ramohalli",12.9229,77.5798,6,7,11,0,2,0,0,0
69,560075,"Jeevabhimanagar,Jeevanbhimanagar,New Thippasandra",12.9229,77.5798,38,14,8,2,0,2,0,0
70,560076,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph...","12.8939,12.9106","77.5978,77.6001",72,35,26,10,6,3,2,5
71,560077,"Doddagubbi,Dr. Shivarama Karanth Nagar,Kothanur",12.9229,77.5798,12,5,7,2,0,0,0,0
72,560078,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou...","12.902,12.9038,12.9057","77.5617,77.5663,77.5709",100,53,43,14,8,1,0,0
73,560079,"Basaveshwaranagar,K H B Colony,Kamakshipalya",12.9229,77.5798,45,14,10,2,0,0,0,0
74,560080,Sadashivanagar,13.0104,77.5806,22,16,13,3,1,2,0,0
75,560082,Bolare,12.7717,77.5053,16,15,11,4,0,0,0,0
76,560083,"Bannerghatta,Gottigere","12.8608,12.9023","77.5896,77.6011",8,4,5,1,0,0,0,0
77,560084,"Kacharakanahalli,Lingarajapuram,St. Thomas Town",13.0096,77.6374,20,5,2,0,0,0,0,0
78,560085,"Banashankari III Stage,Byatarayanapura,Girinag...","12.9299,12.9955,13.0611","77.5523,77.5726,77.593",34,13,13,2,0,0,0,0
79,560086,"Mahalakshmipuram Layout,West of Chord Road II ...",12.9316,77.6041,18,10,10,2,1,1,0,1
80,560087,"Gunjur,Muthusandra,Vartur",12.9316,77.6041,4,2,2,2,2,3,0,0
81,560090,Tarabanahalli,13.0068,77.5971,7,5,1,0,0,0,0,0
82,560091,"Bapagrama,Herohalli,Viswaneedam",13.0583,77.5732,38,8,15,1,0,0,0,0
83,560092,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak...","13.0583,13.0597,13.0611","77.5732,77.5831,77.593",21,14,9,5,0,1,0,1
84,560093,C.V.Raman Nagar,13.0068,77.5971,19,5,7,9,5,0,1,0
85,560094,"ISRO Anthariksha Bhavan,R.M.V. Extension II Stage",13.0068,77.5971,29,18,7,4,3,0,0,1
86,560095,Koramangala VI Bk,13.0068,77.5971,67,44,36,14,2,0,2,2
87,560096,Nandinilayout,13.0134,77.5361,8,1,7,0,0,0,0,0
88,560097,"Chikkabettahalli,Vidyaranyapura",13.0814,77.5566,16,3,5,1,1,0,0,0
89,560098,"Kenchanahalli,Rajarajeshwarinagar",13.1195,77.5837,16,6,5,0,1,0,0,0
90,560099,"Bommasandra Industrial Estate,Hebbagodi,Muthan...","12.8263,12.8311","77.6804,77.6809",24,22,40,11,7,3,2,0
91,560100,"Electronics City,Wipro Limited",12.8458,77.6727,48,38,35,23,6,6,2,5
92,560102,HSR Layout,13.1791,77.0942,98,64,46,11,5,0,0,1
93,560103,"Bellandur,Panathur",12.9255,77.6765,22,28,27,21,7,2,5,7
94,560104,Hampinagar,13.1791,77.0942,5,0,2,1,0,0,0,0
95,560109,Thalaghattapura,13.1791,77.0942,0,0,0,0,0,0,0,0
96,560110,Ullalu Upanagar,13.1791,77.0942,1,0,0,0,0,0,0,0

In [134]:
dataconcat12=dataconcat12.drop(['Area','Pincode'],axis=1)
dataconcat12

,Latitude,Longitude,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,12.9914,77.5944,157,90,91,54,22,14,8,7
1,12.9719,77.5937,47,23,13,6,0,2,0,1
2,13.0097,77.5648,54,22,16,5,2,1,0,0
3,"12.9417,13.5207,14.0998","74.4891,76.0303,77.5714",53,28,27,10,0,2,1,1
4,13.2029,76.9627,37,14,6,0,1,0,1,1
5,13.2029,76.9627,1,1,1,1,0,0,0,0
6,13.2029,76.9627,0,0,0,0,0,0,0,0
7,13.2029,76.9627,101,57,38,16,2,3,0,0
8,13.2029,76.9627,30,13,14,2,1,0,0,0
9,12.9847,77.5491,64,31,19,6,6,0,0,1
10,15.8266,76.2752,62,38,22,7,4,0,0,0
11,15.8266,76.2752,3,0,0,2,0,1,0,0
12,13.0448,77.5474,7,5,7,1,0,0,0,1
13,15.8266,76.2752,2,0,0,0,0,0,0,0
14,15.8266,76.2752,6,1,1,0,0,0,0,0
15,15.8266,76.2752,20,15,6,5,1,1,0,1
16,21.4504,73.7291,36,15,16,7,0,3,0,1
17,15.8266,76.2752,13,7,8,3,0,0,0,0
18,15.8266,76.2752,6,2,4,1,0,0,0,1
19,12.9879,77.5789,33,15,8,5,3,0,0,1
20,12.9879,77.5625,19,1,1,0,0,0,0,0
21,13.11,77.4484,30,23,17,10,2,5,0,1
22,12.975,77.5489,3,7,1,2,0,0,0,0
23,13.11,77.4484,16,14,11,5,0,2,1,0
24,12.9634,77.6025,93,47,50,16,14,6,1,3
25,13.11,77.4484,21,12,6,3,0,0,0,0
26,12.9506,77.5952,38,30,36,9,7,1,1,2
27,13.7952,76.8024,28,15,17,6,7,4,3,2
28,12.944,77.6079,13,11,4,0,0,0,0,2
29,12.938,77.6153,0,23,9,3,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
67,12.9229,77.5798,2,6,2,0,0,2,0,0
68,12.9229,77.5798,6,7,11,0,2,0,0,0
69,12.9229,77.5798,38,14,8,2,0,2,0,0
70,"12.8939,12.9106","77.5978,77.6001",72,35,26,10,6,3,2,5
71,12.9229,77.5798,12,5,7,2,0,0,0,0
72,"12.902,12.9038,12.9057","77.5617,77.5663,77.5709",100,53,43,14,8,1,0,0
73,12.9229,77.5798,45,14,10,2,0,0,0,0
74,13.0104,77.5806,22,16,13,3,1,2,0,0
75,12.7717,77.5053,16,15,11,4,0,0,0,0
76,"12.8608,12.9023","77.5896,77.6011",8,4,5,1,0,0,0,0
77,13.0096,77.6374,20,5,2,0,0,0,0,0
78,"12.9299,12.9955,13.0611","77.5523,77.5726,77.593",34,13,13,2,0,0,0,0
79,12.9316,77.6041,18,10,10,2,1,1,0,1
80,12.9316,77.6041,4,2,2,2,2,3,0,0
81,13.0068,77.5971,7,5,1,0,0,0,0,0
82,13.0583,77.5732,38,8,15,1,0,0,0,0
83,"13.0583,13.0597,13.0611","77.5732,77.5831,77.593",21,14,9,5,0,1,0,1
84,13.0068,77.5971,19,5,7,9,5,0,1,0
85,13.0068,77.5971,29,18,7,4,3,0,0,1
86,13.0068,77.5971,67,44,36,14,2,0,2,2
87,13.0134,77.5361,8,1,7,0,0,0,0,0
88,13.0814,77.5566,16,3,5,1,1,0,0,0
89,13.1195,77.5837,16,6,5,0,1,0,0,0
90,"12.8263,12.8311","77.6804,77.6809",24,22,40,11,7,3,2,0
91,12.8458,77.6727,48,38,35,23,6,6,2,5
92,13.1791,77.0942,98,64,46,11,5,0,0,1
93,12.9255,77.6765,22,28,27,21,7,2,5,7
94,13.1791,77.0942,5,0,2,1,0,0,0,0
95,13.1791,77.0942,0,0,0,0,0,0,0,0
96,13.1791,77.0942,1,0,0,0,0,0,0,0

In [32]:
dataconcat12grouped=dataconcat12.groupby(['Longitude','Latitude']).agg(sum)
dataconcat12grouped=dataconcat12grouped.reset_index(drop=False,inplace=False)
dataconcat12grouped

,Longitude,Latitude,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,73.7291,21.4504,36,15,16,7,0,3,0,1
1,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",53,28,27,10,0,2,1,1
2,76.2752,15.8266,112,63,41,18,5,2,0,2
3,76.5761,10.8368,16,8,6,2,1,1,0,0
4,76.8024,13.7952,28,15,17,6,7,4,3,2
5,76.9627,13.2029,169,85,59,19,4,3,1,1
6,77.0942,13.1791,104,64,48,12,5,0,0,1
7,77.4484,13.11,67,49,34,18,2,7,1,1
8,77.481,12.9121,6,4,6,4,0,0,0,1
9,77.492,12.6859,88,39,42,9,5,5,2,0
10,77.5053,12.7717,16,15,11,4,0,0,0,0
11,77.5113,12.9801,10,7,7,1,0,0,0,0
12,77.5361,13.0134,8,1,7,0,0,0,0,0
13,77.5474,13.0448,7,5,7,1,0,0,0,1
14,77.5489,12.975,3,7,1,2,0,0,0,0
15,77.5491,12.9847,64,31,19,6,6,0,0,1
16,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",34,13,13,2,0,0,0,0
17,77.5566,13.0814,16,3,5,1,1,0,0,0
18,77.5609,13.0323,201,108,105,38,13,7,4,1
19,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",100,53,43,14,8,1,0,0
20,77.5625,12.9879,19,1,1,0,0,0,0,0
21,77.5648,13.0097,54,22,16,5,2,1,0,0
22,77.5732,13.0583,38,8,15,1,0,0,0,0
23,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",21,14,9,5,0,1,0,1
24,77.5789,12.9879,33,15,8,5,3,0,0,1
25,77.5798,12.9229,146,68,59,13,3,6,1,0
26,77.5806,13.0104,22,16,13,3,1,2,0,0
27,77.5837,13.1195,16,6,5,0,1,0,0,0
28,77.5885,12.9278,38,9,15,5,1,0,0,0
29,"77.5896,77.6011","12.8608,12.9023",8,4,5,1,0,0,0,0
30,77.5937,12.9719,47,23,13,6,0,2,0,1
31,77.5944,12.9914,157,90,91,54,22,14,8,7
32,77.5952,12.9506,38,30,36,9,7,1,1,2
33,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",43,20,25,10,1,2,1,0
34,77.5971,13.0068,122,72,51,27,10,0,3,3
35,"77.5978,77.6001","12.8939,12.9106",72,35,26,10,6,3,2,5
36,77.6025,12.9634,93,47,50,16,14,6,1,3
37,77.6041,12.9316,22,12,12,4,3,4,0,1
38,77.6044,12.9985,19,8,2,0,2,0,0,0
39,77.6079,12.944,13,11,4,0,0,0,0,2
40,77.6153,12.938,187,113,74,30,13,8,6,6
41,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1
42,77.6226,13.036,9,11,14,9,4,5,3,1
43,77.6227,12.932,89,46,27,19,8,5,0,2
44,77.6374,13.0096,20,5,2,0,0,0,0,0
45,77.6391,12.9617,51,31,21,8,5,2,4,2
46,77.6487,13.0158,100,45,38,12,2,1,0,1
47,77.6727,12.8458,48,38,35,23,6,6,2,5
48,77.6765,12.9255,22,28,27,21,7,2,5,7
49,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0
50,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3
51,77.7432,12.769,52,29,19,14,6,1,1,0
52,77.7473,12.9716,66,31,52,31,14,5,3,2

In [33]:
dataconcat12grouped=dataconcat12grouped.applymap(lambda x: x if ',' not in str(x) else ','.join(sorted(set(y.strip() for y in(x.split(','))))))
dataconcat12grouped

,Longitude,Latitude,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above
0,73.7291,21.4504,36,15,16,7,0,3,0,1
1,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",53,28,27,10,0,2,1,1
2,76.2752,15.8266,112,63,41,18,5,2,0,2
3,76.5761,10.8368,16,8,6,2,1,1,0,0
4,76.8024,13.7952,28,15,17,6,7,4,3,2
5,76.9627,13.2029,169,85,59,19,4,3,1,1
6,77.0942,13.1791,104,64,48,12,5,0,0,1
7,77.4484,13.11,67,49,34,18,2,7,1,1
8,77.481,12.9121,6,4,6,4,0,0,0,1
9,77.492,12.6859,88,39,42,9,5,5,2,0
10,77.5053,12.7717,16,15,11,4,0,0,0,0
11,77.5113,12.9801,10,7,7,1,0,0,0,0
12,77.5361,13.0134,8,1,7,0,0,0,0,0
13,77.5474,13.0448,7,5,7,1,0,0,0,1
14,77.5489,12.975,3,7,1,2,0,0,0,0
15,77.5491,12.9847,64,31,19,6,6,0,0,1
16,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",34,13,13,2,0,0,0,0
17,77.5566,13.0814,16,3,5,1,1,0,0,0
18,77.5609,13.0323,201,108,105,38,13,7,4,1
19,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",100,53,43,14,8,1,0,0
20,77.5625,12.9879,19,1,1,0,0,0,0,0
21,77.5648,13.0097,54,22,16,5,2,1,0,0
22,77.5732,13.0583,38,8,15,1,0,0,0,0
23,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",21,14,9,5,0,1,0,1
24,77.5789,12.9879,33,15,8,5,3,0,0,1
25,77.5798,12.9229,146,68,59,13,3,6,1,0
26,77.5806,13.0104,22,16,13,3,1,2,0,0
27,77.5837,13.1195,16,6,5,0,1,0,0,0
28,77.5885,12.9278,38,9,15,5,1,0,0,0
29,"77.5896,77.6011","12.8608,12.9023",8,4,5,1,0,0,0,0
30,77.5937,12.9719,47,23,13,6,0,2,0,1
31,77.5944,12.9914,157,90,91,54,22,14,8,7
32,77.5952,12.9506,38,30,36,9,7,1,1,2
33,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",43,20,25,10,1,2,1,0
34,77.5971,13.0068,122,72,51,27,10,0,3,3
35,"77.5978,77.6001","12.8939,12.9106",72,35,26,10,6,3,2,5
36,77.6025,12.9634,93,47,50,16,14,6,1,3
37,77.6041,12.9316,22,12,12,4,3,4,0,1
38,77.6044,12.9985,19,8,2,0,2,0,0,0
39,77.6079,12.944,13,11,4,0,0,0,0,2
40,77.6153,12.938,187,113,74,30,13,8,6,6
41,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1
42,77.6226,13.036,9,11,14,9,4,5,3,1
43,77.6227,12.932,89,46,27,19,8,5,0,2
44,77.6374,13.0096,20,5,2,0,0,0,0,0
45,77.6391,12.9617,51,31,21,8,5,2,4,2
46,77.6487,13.0158,100,45,38,12,2,1,0,1
47,77.6727,12.8458,48,38,35,23,6,6,2,5
48,77.6765,12.9255,22,28,27,21,7,2,5,7
49,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0
50,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3
51,77.7432,12.769,52,29,19,14,6,1,1,0
52,77.7473,12.9716,66,31,52,31,14,5,3,2

3.1.2 Preparing dataconcat14:merging dataset1 and dataset3 and then adding the number of food outlets by Longitude,Latitude and Pincode.

In [34]:
datasetfirst=dataset1
datasetfirst

,Country,Pincode,Area,Bangalore-Division,Latitude,Longitude
0,IN,560001,Bangalore G.P.O.,Bangalore North,12.9914,77.5944
1,IN,560001,Legislators Home,Bangalore North,12.9914,77.5944
2,IN,560001,Vasanthanagar,Bangalore North,12.9914,77.5944
3,IN,560001,Mahatma Gandhi Road,Bangalore North,12.9914,77.5944
4,IN,560001,Vidhana Soudha,Bangalore North,12.9914,77.5944
5,IN,560001,Rajbhavan (Bangalore),Bangalore North,12.9914,77.5944
6,IN,560001,HighCourt,Bangalore North,12.9914,77.5944
7,IN,560001,Cubban Road,Bangalore North,12.9914,77.5944
8,IN,560001,Bangalore Bazaar,Bangalore North,12.9914,77.5944
9,IN,560001,CMM Court Complex,Bangalore North,12.9914,77.5944
10,IN,560001,Dr. Ambedkar Veedhi,Bangalore North,12.9914,77.5944
11,IN,560002,Bangalore City,Bangalore North,12.9719,77.5937
12,IN,560002,Bangalore Corporation Building,Bangalore South,12.9719,77.5937
13,IN,560002,Sri Jayachamarajendra Road,Bangalore South,12.9719,77.5937
14,IN,560003,Palace Guttahalli,Bangalore North,13.0097,77.5648
15,IN,560003,Malleswaram,Bangalore North,13.0097,77.5648
16,IN,560003,Swimming Pool Extn,Bangalore North,13.0097,77.5648
17,IN,560003,Vyalikaval Extn,Bangalore North,13.0097,77.5648
18,IN,560004,Pampamahakavi Road,Bangalore South,13.5207,76.0303
19,IN,560004,Thyagarajnagar,Bangalore South,13.5207,76.0303
20,IN,560004,Mavalli,Bangalore South,14.0998,74.4891
21,IN,560004,Basavanagudi,Bangalore South,12.9417,77.5714
22,IN,560005,Fraser Town,Bangalore North,13.2029,76.9627
23,IN,560006,J.C.Nagar,Bangalore North,13.2029,76.9627
24,IN,560006,Training Command IAF,Bangalore North,13.2029,76.9627
25,IN,560007,Agram,Bangalore South,13.2029,76.9627
26,IN,560007,Air Force Hospital,Bangalore North,13.2029,76.9627
27,IN,560008,Hulsur Bazaar,Bangalore North,13.2029,76.9627
28,IN,560008,H.A.L II Stage,Bangalore North,13.2029,76.9627
29,IN,560009,K. G. Road,Bangalore North,13.2029,76.9627
...,...,...,...,...,...,...
203,IN,560087,Gunjur,Bangalore North,12.9316,77.6041
204,IN,560090,Tarabanahalli,Bangalore North,13.0068,77.5971
205,IN,560091,Herohalli,Bangalore North,13.0583,77.5732
206,IN,560091,Bapagrama,Bangalore North,13.0583,77.5732
207,IN,560091,Viswaneedam,Bangalore North,13.0583,77.5732
208,IN,560091,Herohalli,Bangalore north,13.0583,77.5732
209,IN,560092,Amruthahalli,Bangalore North,13.0597,77.5831
210,IN,560092,Byatarayanapura,Bangalore North,13.0611,77.593
211,IN,560092,Kodigehalli,Bangalore North,13.0583,77.5732
212,IN,560092,Sahakaranagar P.O,Bangalore North,13.0597,77.5831
213,IN,560093,C.V.Raman Nagar,Bangalore North,13.0068,77.5971
214,IN,560094,ISRO Anthariksha Bhavan,Bangalore North,13.0068,77.5971
215,IN,560094,R.M.V. Extension II Stage,Bangalore North,13.0068,77.5971
216,IN,560095,Koramangala VI Bk,Bangalore South,13.0068,77.5971
217,IN,560096,Nandinilayout,Bangalore North,13.0134,77.5361
218,IN,560097,Chikkabettahalli,Bangalore North,13.0814,77.5566
219,IN,560097,Vidyaranyapura,Bangalore North,13.0814,77.5566
220,IN,560098,Rajarajeshwarinagar,Bangalore South,13.1195,77.5837
221,IN,560098,Kenchanahalli,Bangalore South,13.1195,77.5837
222,IN,560099,Bommasandra Industrial Estate,Bangalore South,12.8311,77.6804
223,IN,560099,Hebbagodi,Bangalore South,12.8263,77.6809
224,IN,560099,Muthanallur,Bangalore South,12.8311,77.6804
225,IN,560100,Electronics City,Bangalore South,12.8458,77.6727
226,IN,560100,Wipro Limited,Bangalore South,12.8458,77.6727
227,IN,560102,HSR Layout,Bangalore South,13.1791,77.0942
228,IN,560103,Bellandur,Bangalore South,12.9255,77.6765
229,IN,560103,Panathur,Bangalore South,12.9255,77.6765
230,IN,560104,Hampinagar,Bangalore North,13.1791,77.0942
231,IN,560109,Thalaghattapura,Bangalore South,13.1791,77.0942
232,IN,560110,Ullalu Upanagar,Bangalore North,13.1791,77.0942

In [35]:
datasetfirst['Longitude'].dtype

dtype('O')

In [36]:
datasetfirst['Longitude']=datasetfirst['Longitude'].astype(float)
datasetfirst['Latitude']=datasetfirst['Latitude'].astype(float)
datasetfirst['Pincode']=datasetfirst['Pincode'].astype(str)

In [37]:
datasetsecond=datasetfirst.groupby(['Longitude','Latitude'],sort=False).agg(','.join)
datasetsecond=datasetsecond.drop(['Country','Area','Bangalore-Division'], axis=1)
datasetsecond=datasetsecond.applymap(lambda x: x if ',' not in str(x) else ','.join(sorted(set(y.strip() for y in(x.split(','))))))
datasetsecond=datasetsecond.reset_index(drop=False,inplace=False)
datasetsecond

    Longitude  Latitude                                            Pincode
0     77.5944   12.9914                                             560001
1     77.5937   12.9719                                             560002
2     77.5648   13.0097                                             560003
3     76.0303   13.5207                                             560004
4     74.4891   14.0998                                             560004
5     77.5714   12.9417                                             560004
6     76.9627   13.2029                 560005,560006,560007,560008,560009
7     77.5491   12.9847                                             560010
8     76.2752   15.8266   560011,560012,560014,560015,560016,560018,560019
9     77.5474   13.0448                                             560013
10    73.7291   21.4504                                             560017
11    77.5789   12.9879                                             560020
12    77.5625   12.9879                                             560021
13    77.4484   13.1100                               560022,560024,560026
14    77.5489   12.9750                                             560023
15    77.6025   12.9634                                             560025
16    77.5952   12.9506                                             560027
17    76.8024   13.7952                                             560029
18    77.6079   12.9440                                             560030
19    77.6153   12.9380   560032,560033,560035,560036,560037,560038,560039
20    77.6227   12.9320                                             560034
21    77.4920   12.6859                               560040,560042,560047
22    77.5885   12.9278                                             560041
23    77.6487   13.0158                                             560043
24    77.6226   13.0360                                             560045
25    77.6044   12.9985                                             560046
26    77.7164   12.9944                                             560048
27    77.6869   12.9923                                             560048
28    76.5761   10.8368                                             560049
29    77.5609   13.0323  560050,560051,560053,560054,560055,560056,5600...
..        ...       ...                                                ...
38    77.6209   12.9240                                             560068
39    77.6299   12.8931                                             560068
40    77.5798   12.9229          560070,560073,560074,560075,560077,560079
41    77.6391   12.9617                                             560071
42    77.5113   12.9801                                             560072
43    77.5978   12.8939                                             560076
44    77.6001   12.9106                                             560076
45    77.5709   12.9020                                             560078
46    77.5617   12.9057                                             560078
47    77.5663   12.9038                                             560078
48    77.5806   13.0104                                             560080
49    77.5053   12.7717                                             560082
50    77.5896   12.8608                                             560083
51    77.6011   12.9023                                             560083
52    77.6374   13.0096                                             560084
53    77.5930   13.0611                                      560085,560092
54    77.5523   12.9299                                             560085
55    77.5726   12.9955                                             560085
56    77.6041   12.9316                                      560086,560087
57    77.5971   13.0068                        560090,560093,560094,560095
58    77.5732   13.0583                                      560091,560092
59    77.5831   13.0597                                             560092
60    77.5361   13.0134                                             560096
61    77.5566   13.0814                                             560097
62    77.5837   13.1195                                             560098
63    77.6804   12.8311                                             560099
64    77.6809   12.8263                                             560099
65    77.6727   12.8458                                             560100
66    77.0942   13.1791                        560102,560104,560109,560110
67    77.6765   12.9255                                             560103

[68 rows x 3 columns]

In [38]:
dataconcat13=pd.concat([datasetsecond,dataset3],axis=1)
dataconcat13=dataconcat13.drop(['longitude','latitude'],axis=1)
dataconcat13

,Longitude,Latitude,Pincode,Number of Food Outlets
0,77.5944,12.9914,560001,31
1,77.5937,12.9719,560002,49
2,77.5648,13.0097,560003,47
3,76.0303,13.5207,560004,0
4,74.4891,14.0998,560004,0
5,77.5714,12.9417,560004,35
6,76.9627,13.2029,"560005,560006,560007,560008,560009",0
7,77.5491,12.9847,560010,37
8,76.2752,15.8266,"560011,560012,560014,560015,560016,560018,560019",0
9,77.5474,13.0448,560013,9
10,73.7291,21.4504,560017,0
11,77.5789,12.9879,560020,42
12,77.5625,12.9879,560021,44
13,77.4484,13.1100,"560022,560024,560026",0
14,77.5489,12.9750,560023,32
15,77.6025,12.9634,560025,48
16,77.5952,12.9506,560027,31
17,76.8024,13.7952,560029,0
18,77.6079,12.9440,560030,50
19,77.6153,12.9380,"560032,560033,560035,560036,560037,560038,560039",50
20,77.6227,12.9320,560034,50
21,77.4920,12.6859,"560040,560042,560047",0
22,77.5885,12.9278,560041,50
23,77.6487,13.0158,560043,28
24,77.6226,13.0360,560045,20
25,77.6044,12.9985,560046,37
26,77.7164,12.9944,560048,20
27,77.6869,12.9923,560048,21
28,76.5761,10.8368,560049,0
29,77.5609,13.0323,"560050,560051,560053,560054,560055,560056,5600...",40
...,...,...,...,...
38,77.6209,12.9240,560068,50
39,77.6299,12.8931,560068,19
40,77.5798,12.9229,"560070,560073,560074,560075,560077,560079",50
41,77.6391,12.9617,560071,50
42,77.5113,12.9801,560072,9
43,77.5978,12.8939,560076,48
44,77.6001,12.9106,560076,50
45,77.5709,12.9020,560078,21
46,77.5617,12.9057,560078,17
47,77.5663,12.9038,560078,19
48,77.5806,13.0104,560080,37
49,77.5053,12.7717,560082,0
50,77.5896,12.8608,560083,12
51,77.6011,12.9023,560083,50
52,77.6374,13.0096,560084,32
53,77.5930,13.0611,"560085,560092",16
54,77.5523,12.9299,560085,21
55,77.5726,12.9955,560085,37
56,77.6041,12.9316,"560086,560087",50
57,77.5971,13.0068,"560090,560093,560094,560095",33
58,77.5732,13.0583,"560091,560092",19
59,77.5831,13.0597,560092,18
60,77.5361,13.0134,560096,22
61,77.5566,13.0814,560097,7
62,77.5837,13.1195,560098,5
63,77.6804,12.8311,560099,19
64,77.6809,12.8263,560099,9
65,77.6727,12.8458,560100,44
66,77.0942,13.1791,"560102,560104,560109,560110",0
67,77.6765,12.9255,560103,33

In [39]:
dataconcat13=dataconcat13.applymap(lambda x: x if ',' not in str(x) else ','.join(sorted(set(y.strip() for y in(x.split(','))))))
dataconcat13

,Longitude,Latitude,Pincode,Number of Food Outlets
0,77.5944,12.9914,560001,31
1,77.5937,12.9719,560002,49
2,77.5648,13.0097,560003,47
3,76.0303,13.5207,560004,0
4,74.4891,14.0998,560004,0
5,77.5714,12.9417,560004,35
6,76.9627,13.2029,"560005,560006,560007,560008,560009",0
7,77.5491,12.9847,560010,37
8,76.2752,15.8266,"560011,560012,560014,560015,560016,560018,560019",0
9,77.5474,13.0448,560013,9
10,73.7291,21.4504,560017,0
11,77.5789,12.9879,560020,42
12,77.5625,12.9879,560021,44
13,77.4484,13.1100,"560022,560024,560026",0
14,77.5489,12.9750,560023,32
15,77.6025,12.9634,560025,48
16,77.5952,12.9506,560027,31
17,76.8024,13.7952,560029,0
18,77.6079,12.9440,560030,50
19,77.6153,12.9380,"560032,560033,560035,560036,560037,560038,560039",50
20,77.6227,12.9320,560034,50
21,77.4920,12.6859,"560040,560042,560047",0
22,77.5885,12.9278,560041,50
23,77.6487,13.0158,560043,28
24,77.6226,13.0360,560045,20
25,77.6044,12.9985,560046,37
26,77.7164,12.9944,560048,20
27,77.6869,12.9923,560048,21
28,76.5761,10.8368,560049,0
29,77.5609,13.0323,"560050,560051,560053,560054,560055,560056,5600...",40
...,...,...,...,...
38,77.6209,12.9240,560068,50
39,77.6299,12.8931,560068,19
40,77.5798,12.9229,"560070,560073,560074,560075,560077,560079",50
41,77.6391,12.9617,560071,50
42,77.5113,12.9801,560072,9
43,77.5978,12.8939,560076,48
44,77.6001,12.9106,560076,50
45,77.5709,12.9020,560078,21
46,77.5617,12.9057,560078,17
47,77.5663,12.9038,560078,19
48,77.5806,13.0104,560080,37
49,77.5053,12.7717,560082,0
50,77.5896,12.8608,560083,12
51,77.6011,12.9023,560083,50
52,77.6374,13.0096,560084,32
53,77.5930,13.0611,"560085,560092",16
54,77.5523,12.9299,560085,21
55,77.5726,12.9955,560085,37
56,77.6041,12.9316,"560086,560087",50
57,77.5971,13.0068,"560090,560093,560094,560095",33
58,77.5732,13.0583,"560091,560092",19
59,77.5831,13.0597,560092,18
60,77.5361,13.0134,560096,22
61,77.5566,13.0814,560097,7
62,77.5837,13.1195,560098,5
63,77.6804,12.8311,560099,19
64,77.6809,12.8263,560099,9
65,77.6727,12.8458,560100,44
66,77.0942,13.1791,"560102,560104,560109,560110",0
67,77.6765,12.9255,560103,33

In [40]:
dataconcat13=dataconcat13.drop(['Longitude','Latitude'], axis=1)
dataconcat13

                                              Pincode  Number of Food Outlets
0                                              560001                      31
1                                              560002                      49
2                                              560003                      47
3                                              560004                       0
4                                              560004                       0
5                                              560004                      35
6                  560005,560006,560007,560008,560009                       0
7                                              560010                      37
8    560011,560012,560014,560015,560016,560018,560019                       0
9                                              560013                       9
10                                             560017                       0
11                                             560020                      42
12                                             560021                      44
13                               560022,560024,560026                       0
14                                             560023                      32
15                                             560025                      48
16                                             560027                      31
17                                             560029                       0
18                                             560030                      50
19   560032,560033,560035,560036,560037,560038,560039                      50
20                                             560034                      50
21                               560040,560042,560047                       0
22                                             560041                      50
23                                             560043                      28
24                                             560045                      20
25                                             560046                      37
26                                             560048                      20
27                                             560048                      21
28                                             560049                       0
29  560050,560051,560053,560054,560055,560056,5600...                      40
..                                                ...                     ...
38                                             560068                      50
39                                             560068                      19
40          560070,560073,560074,560075,560077,560079                      50
41                                             560071                      50
42                                             560072                       9
43                                             560076                      48
44                                             560076                      50
45                                             560078                      21
46                                             560078                      17
47                                             560078                      19
48                                             560080                      37
49                                             560082                       0
50                                             560083                      12
51                                             560083                      50
52                                             560084                      32
53                                      560085,560092                      16
54                                             560085                      21
55                                             560085                      37
56                                      560086,560087                      50
57                        560090,560093,560094,560095                      33
58                                      560091,560092                      19
59                                             560092                      18
60                                             560096                      22
61                                             560097                       7
62                                             560098                       5
63                                             560099                      19
64                                             560099                       9
65                                             560100                      44
66                        560102,560104,560109,560110                       0
67                                             560103                      33

[68 rows x 2 columns]

In [41]:
dataconcat13=dataconcat13.groupby(['Pincode'],sort=False).agg(sum)
dataconcat13=dataconcat13.reset_index(drop=False, inplace=False)
dataconcat13=dataconcat13.applymap(lambda x: x if ',' not in str(x) else ','.join(sorted(set(y.strip() for y in(x.split(','))))))
dataconcat13

                                              Pincode  Number of Food Outlets
0                                              560001                      31
1                                              560002                      49
2                                              560003                      47
3                                              560004                      35
4                  560005,560006,560007,560008,560009                       0
5                                              560010                      37
6    560011,560012,560014,560015,560016,560018,560019                       0
7                                              560013                       9
8                                              560017                       0
9                                              560020                      42
10                                             560021                      44
11                               560022,560024,560026                       0
12                                             560023                      32
13                                             560025                      48
14                                             560027                      31
15                                             560029                       0
16                                             560030                      50
17   560032,560033,560035,560036,560037,560038,560039                      50
18                                             560034                      50
19                               560040,560042,560047                       0
20                                             560041                      50
21                                             560043                      28
22                                             560045                      20
23                                             560046                      37
24                                             560048                      41
25                                             560049                       0
26  560050,560051,560053,560054,560055,560056,5600...                      40
27                                             560060                       8
28                 560061,560062,560063,560065,560067                       0
29                                             560064                      11
30                                             560066                      22
31                                             560068                      95
32          560070,560073,560074,560075,560077,560079                      50
33                                             560071                      50
34                                             560072                       9
35                                             560076                      98
36                                             560078                      57
37                                             560080                      37
38                                             560082                       0
39                                             560083                      62
40                                             560084                      32
41                                      560085,560092                      16
42                                             560085                      58
43                                      560086,560087                      50
44                        560090,560093,560094,560095                      33
45                                      560091,560092                      19
46                                             560092                      18
47                                             560096                      22
48                                             560097                       7
49                                             560098                       5
50                                             560099                      28
51                                             560100                      44
52                        560102,560104,560109,560110                       0
53                                             560103                      33

In [42]:
dataconcat13=dataconcat13[dataconcat13.Pincode !='560085,560092']
dataconcat13=dataconcat13.set_value(42,'Number of Food Outlets',74)
dataconcat13=dataconcat13.set_value(46,'Number of Food Outlets',53)
dataconcat13

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  from ipykernel import kernelapp as app
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()

                                              Pincode  Number of Food Outlets
0                                              560001                      31
1                                              560002                      49
2                                              560003                      47
3                                              560004                      35
4                  560005,560006,560007,560008,560009                       0
5                                              560010                      37
6    560011,560012,560014,560015,560016,560018,560019                       0
7                                              560013                       9
8                                              560017                       0
9                                              560020                      42
10                                             560021                      44
11                               560022,560024,560026                       0
12                                             560023                      32
13                                             560025                      48
14                                             560027                      31
15                                             560029                       0
16                                             560030                      50
17   560032,560033,560035,560036,560037,560038,560039                      50
18                                             560034                      50
19                               560040,560042,560047                       0
20                                             560041                      50
21                                             560043                      28
22                                             560045                      20
23                                             560046                      37
24                                             560048                      41
25                                             560049                       0
26  560050,560051,560053,560054,560055,560056,5600...                      40
27                                             560060                       8
28                 560061,560062,560063,560065,560067                       0
29                                             560064                      11
30                                             560066                      22
31                                             560068                      95
32          560070,560073,560074,560075,560077,560079                      50
33                                             560071                      50
34                                             560072                       9
35                                             560076                      98
36                                             560078                      57
37                                             560080                      37
38                                             560082                       0
39                                             560083                      62
40                                             560084                      32
42                                             560085                      74
43                                      560086,560087                      50
44                        560090,560093,560094,560095                      33
45                                      560091,560092                      19
46                                             560092                      53
47                                             560096                      22
48                                             560097                       7
49                                             560098                       5
50                                             560099                      28
51                                             560100                      44
52                        560102,560104,560109,560110                       0
53                                             560103                      33

In [43]:
dataconcat14=dataconcat13.replace({'560091,560092': 560091})
dataconcat14=dataconcat14.reset_index(drop=True,inplace=False)
dataconcat14

                                              Pincode  Number of Food Outlets
0                                              560001                      31
1                                              560002                      49
2                                              560003                      47
3                                              560004                      35
4                  560005,560006,560007,560008,560009                       0
5                                              560010                      37
6    560011,560012,560014,560015,560016,560018,560019                       0
7                                              560013                       9
8                                              560017                       0
9                                              560020                      42
10                                             560021                      44
11                               560022,560024,560026                       0
12                                             560023                      32
13                                             560025                      48
14                                             560027                      31
15                                             560029                       0
16                                             560030                      50
17   560032,560033,560035,560036,560037,560038,560039                      50
18                                             560034                      50
19                               560040,560042,560047                       0
20                                             560041                      50
21                                             560043                      28
22                                             560045                      20
23                                             560046                      37
24                                             560048                      41
25                                             560049                       0
26  560050,560051,560053,560054,560055,560056,5600...                      40
27                                             560060                       8
28                 560061,560062,560063,560065,560067                       0
29                                             560064                      11
30                                             560066                      22
31                                             560068                      95
32          560070,560073,560074,560075,560077,560079                      50
33                                             560071                      50
34                                             560072                       9
35                                             560076                      98
36                                             560078                      57
37                                             560080                      37
38                                             560082                       0
39                                             560083                      62
40                                             560084                      32
41                                             560085                      74
42                                      560086,560087                      50
43                        560090,560093,560094,560095                      33
44                                             560091                      19
45                                             560092                      53
46                                             560096                      22
47                                             560097                       7
48                                             560098                       5
49                                             560099                      28
50                                             560100                      44
51                        560102,560104,560109,560110                       0
52                                             560103                      33

Obtaining the areas in Bangalore according to Longitude,Latitude and Pincode

In [44]:
dataf3['Pincode']=dataf3['Pincode'].astype(str)

In [45]:
dataf4=dataf3.groupby(['Longitude', 'Latitude'],sort=False).agg(','.join)
dataf5=dataf4.reset_index(drop=False, inplace=False)
dataf5

,Longitude,Latitude,Pincode,Area
0,77.5944,12.9914,560001,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,77.5937,12.9719,560002,"Bangalore City,Bangalore Corporation Building,..."
2,77.5648,13.0097,560003,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",560004,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,76.9627,13.2029,"560005,560006,560007,560008,560009","Fraser Town,J.C.Nagar,Training Command IAF,Agr..."
5,77.5491,12.9847,560010,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,76.2752,15.8266,"560011,560012,560014,560015,560016,560018,560019","Jayangar III Block,Madhavan Park,Science Insti..."
7,77.5474,13.0448,560013,Jalahalli
8,73.7291,21.4504,560017,"NAL,Vimanapura"
9,77.5789,12.9879,560020,Seshadripuram
10,77.5625,12.9879,560021,"Gayathrinagar,Srirampuram"
11,77.4484,13.11,"560022,560024,560026","Yeshwanthpur Bazar,Yeswanthpura,Anandnagar (Ba..."
12,77.5489,12.975,560023,Magadi Road
13,77.6025,12.9634,560025,"CMP Centre And School,Museum Road,Richmond Town"
14,77.5952,12.9506,560027,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,76.8024,13.7952,560029,"Dharmaram College,Tavarekere"
16,77.6079,12.944,560030,Adugodi
17,77.6153,12.938,"560032,560033,560035,560036,560037,560038,560039","Kanakanagar,P&T Col. Kavalbyrasandra,R T Nagar..."
18,77.6227,12.932,560034,"Agara,Koramangala,Koramangala I Block,St. John..."
19,77.492,12.6859,"560040,560042,560047","Chandra Lay Out,Vijayanagar (Bangalore),Vijaya..."
20,77.5885,12.9278,560041,"Jayanagar,Tilaknagar (Bangalore)"
21,77.6487,13.0158,560043,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,77.6226,13.036,560045,"Arabic College,Nagawara,Venkateshapura"
23,77.6044,12.9985,560046,Benson Town
24,"77.6869,77.7164","12.9923,12.9944",560048,"Hoodi,Mahadevapura"
25,76.5761,10.8368,560049,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,77.5609,13.0323,"560050,560051,560053,560054,560055,560056,5600...","Ashoknagar (Bangalore),Banashankari,Dasarahall..."
27,77.481,12.9121,560060,Chudenapura
28,77.7432,12.769,"560061,560062,560063,560065,560067","Chikkalasandra,Subramanyapura,Doddakallasandra..."
29,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",560064,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,77.7473,12.9716,560066,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",560068,"Begur,Bommanahalli,Hongasandra,Madivala"
32,77.5798,12.9229,"560070,560073,560074,560075,560077,560079","B Sk II Stage,Jayanagar West,Padmanabhnagar,Ty..."
33,77.6391,12.9617,560071,Domlur
34,77.5113,12.9801,560072,Nagarbhavi
35,"77.5978,77.6001","12.8939,12.9106",560076,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",560078,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,77.5806,13.0104,560080,Sadashivanagar
38,77.5053,12.7717,560082,Bolare
39,"77.5896,77.6011","12.8608,12.9023",560083,"Bannerghatta,Gottigere"
40,77.6374,13.0096,560084,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",560085,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,77.6041,12.9316,"560086,560087","Mahalakshmipuram Layout,West of Chord Road II ..."
43,77.5971,13.0068,"560090,560093,560094,560095","Tarabanahalli,C.V.Raman Nagar,ISRO Anthariksha..."
44,77.5732,13.0583,560091,"Bapagrama,Herohalli,Viswaneedam"
45,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",560092,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,77.5361,13.0134,560096,Nandinilayout
47,77.5566,13.0814,560097,"Chikkabettahalli,Vidyaranyapura"
48,77.5837,13.1195,560098,"Kenchanahalli,Rajarajeshwarinagar"
49,"77.6804,77.6809","12.8263,12.8311",560099,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,77.6727,12.8458,560100,"Electronics City,Wipro Limited"
51,77.0942,13.1791,"560102,560104,560109,560110","HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,77.6765,12.9255,560103,"Bellandur,Panathur"

In [46]:
dataf6=dataf5.applymap(lambda x: x if ',' not in str(x) else ','.join(sorted(set(y.strip() for y in(x.split(','))))))
dataf6

,Longitude,Latitude,Pincode,Area
0,77.5944,12.9914,560001,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,77.5937,12.9719,560002,"Bangalore City,Bangalore Corporation Building,..."
2,77.5648,13.0097,560003,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",560004,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,76.9627,13.2029,"560005,560006,560007,560008,560009","Agram,Air Force Hospital,Bangalore Dist Office..."
5,77.5491,12.9847,560010,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,76.2752,15.8266,"560011,560012,560014,560015,560016,560018,560019","Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,77.5474,13.0448,560013,Jalahalli
8,73.7291,21.4504,560017,"NAL,Vimanapura"
9,77.5789,12.9879,560020,Seshadripuram
10,77.5625,12.9879,560021,"Gayathrinagar,Srirampuram"
11,77.4484,13.11,"560022,560024,560026","Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,77.5489,12.975,560023,Magadi Road
13,77.6025,12.9634,560025,"CMP Centre And School,Museum Road,Richmond Town"
14,77.5952,12.9506,560027,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,76.8024,13.7952,560029,"Dharmaram College,Tavarekere"
16,77.6079,12.944,560030,Adugodi
17,77.6153,12.938,"560032,560033,560035,560036,560037,560038,560039","Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,77.6227,12.932,560034,"Agara,Koramangala,Koramangala I Block,St. John..."
19,77.492,12.6859,"560040,560042,560047","Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,77.5885,12.9278,560041,"Jayanagar,Tilaknagar (Bangalore)"
21,77.6487,13.0158,560043,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,77.6226,13.036,560045,"Arabic College,Nagawara,Venkateshapura"
23,77.6044,12.9985,560046,Benson Town
24,"77.6869,77.7164","12.9923,12.9944",560048,"Hoodi,Mahadevapura"
25,76.5761,10.8368,560049,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,77.5609,13.0323,"560050,560051,560053,560054,560055,560056,5600...","Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,77.481,12.9121,560060,Chudenapura
28,77.7432,12.769,"560061,560062,560063,560065,560067","A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",560064,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,77.7473,12.9716,560066,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",560068,"Begur,Bommanahalli,Hongasandra,Madivala"
32,77.5798,12.9229,"560070,560073,560074,560075,560077,560079","B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,77.6391,12.9617,560071,Domlur
34,77.5113,12.9801,560072,Nagarbhavi
35,"77.5978,77.6001","12.8939,12.9106",560076,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",560078,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,77.5806,13.0104,560080,Sadashivanagar
38,77.5053,12.7717,560082,Bolare
39,"77.5896,77.6011","12.8608,12.9023",560083,"Bannerghatta,Gottigere"
40,77.6374,13.0096,560084,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",560085,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,77.6041,12.9316,"560086,560087","Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,77.5971,13.0068,"560090,560093,560094,560095","C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,77.5732,13.0583,560091,"Bapagrama,Herohalli,Viswaneedam"
45,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",560092,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,77.5361,13.0134,560096,Nandinilayout
47,77.5566,13.0814,560097,"Chikkabettahalli,Vidyaranyapura"
48,77.5837,13.1195,560098,"Kenchanahalli,Rajarajeshwarinagar"
49,"77.6804,77.6809","12.8263,12.8311",560099,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,77.6727,12.8458,560100,"Electronics City,Wipro Limited"
51,77.0942,13.1791,"560102,560104,560109,560110","HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,77.6765,12.9255,560103,"Bellandur,Panathur"

In [75]:
datafinal=pd.concat([dataconcat14,dataconcat12grouped],axis=1)
dataArea=dataf6['Area']
datafinal1=pd.concat([datafinal,dataArea],axis=1)
datafinal1

,Pincode,Number of Food Outlets,Longitude,Latitude,E.no 1-50,E.no 51-100,E.no 101-250,E.no 251-500,E.no 501-1000,E.no 1001-2500,E.no 2501-5000,E.no 5001 & above,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,560002,49,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,560013,9,77.4484,13.11,67,49,34,18,2,7,1,1,Jalahalli
8,560017,0,77.481,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,560020,42,77.492,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,560027,31,77.5489,12.975,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,560030,50,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",34,13,13,2,0,0,0,0,Adugodi
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,"560040,560042,560047",0,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",21,14,9,5,0,1,0,1,Benson Town
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,"77.5896,77.6011","12.8608,12.9023",8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,560071,50,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",43,20,25,10,1,2,1,0,Domlur
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,560076,98,"77.5978,77.6001","12.8939,12.9106",72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,560083,62,77.6079,12.944,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.938,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,"560086,560087",50,77.6226,13.036,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,"560090,560093,560094,560095",33,77.6227,12.932,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,560099,28,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,560100,44,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,"560102,560104,560109,560110",0,77.7432,12.769,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

3.2 Applying the K-means Clustering algorithm on the final dataset- datafinal1

Importing libraries

In [76]:
import numpy as np
from sklearn.cluster import KMeans

Renaming employee number columns in datafinal1 for easier computation.

In [77]:
datafinal1=datafinal1.rename(columns={'E.no 1-50': 'One'})
datafinal1=datafinal1.rename(columns={'E.no 51-100': 'Two'})
datafinal1=datafinal1.rename(columns={'E.no 101-250': 'Three'})
datafinal1=datafinal1.rename(columns={'E.no 251-500': 'Four'})
datafinal1=datafinal1.rename(columns={'E.no 501-1000': 'Five'})
datafinal1=datafinal1.rename(columns={'E.no 1001-2500': 'Six'})
datafinal1=datafinal1.rename(columns={'E.no 2501-5000': 'Seven'})
datafinal1

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,E.no 5001 & above,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,560002,49,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,560013,9,77.4484,13.11,67,49,34,18,2,7,1,1,Jalahalli
8,560017,0,77.481,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,560020,42,77.492,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,560027,31,77.5489,12.975,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,560030,50,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",34,13,13,2,0,0,0,0,Adugodi
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,"560040,560042,560047",0,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",21,14,9,5,0,1,0,1,Benson Town
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,"77.5896,77.6011","12.8608,12.9023",8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,560071,50,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",43,20,25,10,1,2,1,0,Domlur
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,560076,98,"77.5978,77.6001","12.8939,12.9106",72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,560083,62,77.6079,12.944,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.938,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,"560086,560087",50,77.6226,13.036,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,"560090,560093,560094,560095",33,77.6227,12.932,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,560099,28,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,560100,44,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,"560102,560104,560109,560110",0,77.7432,12.769,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

In [78]:
datafinal1=datafinal1.rename(columns={'E.no 5001 & above': 'Eight'})
datafinal1

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,560002,49,"74.4891,76.0303,77.5714","12.9417,13.5207,14.0998",53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,560013,9,77.4484,13.11,67,49,34,18,2,7,1,1,Jalahalli
8,560017,0,77.481,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,560020,42,77.492,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,560027,31,77.5489,12.975,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,560030,50,"77.5523,77.5726,77.593","12.9299,12.9955,13.0611",34,13,13,2,0,0,0,0,Adugodi
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,"560040,560042,560047",0,"77.5617,77.5663,77.5709","12.902,12.9038,12.9057",100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,"77.5732,77.5831,77.593","13.0583,13.0597,13.0611",21,14,9,5,0,1,0,1,Benson Town
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,"77.5896,77.6011","12.8608,12.9023",8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,560071,50,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",43,20,25,10,1,2,1,0,Domlur
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,560076,98,"77.5978,77.6001","12.8939,12.9106",72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,560083,62,77.6079,12.944,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.938,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,"560086,560087",50,77.6226,13.036,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,"560090,560093,560094,560095",33,77.6227,12.932,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,560099,28,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,560100,44,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,"560102,560104,560109,560110",0,77.7432,12.769,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

Removing Longitudes and their corresponding Latitudes from Coulmns :'Longitude','Latitude'of datafinal1 for easier compuation of clustering algorithm.
note:Both, number of companies and food outlets in various areas(with pincodes) of Bangalore (having more than 1 longitude and latitude) remain unaffected.

In [79]:
datafinal1=datafinal1.replace({'74.4891,76.0303,77.5714': 74.4891})
datafinal1=datafinal1.replace({'12.9417,13.5207,14.0998': 12.9417})
datafinal1=datafinal1.replace({'77.5523,77.5726,77.593': 77.5523})
datafinal1=datafinal1.replace({'12.9299,12.9955,13.0611': 12.9299})
datafinal1=datafinal1.replace({'77.5617,77.5663,77.5709': 77.5617})
datafinal1=datafinal1.replace({'12.902,12.9038,12.9057': 12.902})
datafinal1=datafinal1.replace({'77.5732,77.5831,77.593': 77.5732})
datafinal1=datafinal1.replace({'77.5896,77.6011': 77.5896})
datafinal1=datafinal1.replace({'12.8608,12.9023': 12.8608})
datafinal1

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,560002,49,74.4891,12.9417,53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,560013,9,77.4484,13.11,67,49,34,18,2,7,1,1,Jalahalli
8,560017,0,77.481,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,560020,42,77.492,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,560027,31,77.5489,12.975,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,560030,50,77.5523,12.9299,34,13,13,2,0,0,0,0,Adugodi
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,"560040,560042,560047",0,77.5617,12.902,100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,77.5732,"13.0583,13.0597,13.0611",21,14,9,5,0,1,0,1,Benson Town
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,77.5896,12.8608,8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,560071,50,"77.5963,78.0988,78.6014","11.5941,12.3477,13.1013",43,20,25,10,1,2,1,0,Domlur
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,560076,98,"77.5978,77.6001","12.8939,12.9106",72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,560083,62,77.6079,12.944,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.938,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,"560086,560087",50,77.6226,13.036,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,"560090,560093,560094,560095",33,77.6227,12.932,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,560099,28,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,560100,44,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,"560102,560104,560109,560110",0,77.7432,12.769,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

In [80]:
datafinal1=datafinal1.replace({'77.5963,78.0988,78.6014': 77.5963})
datafinal1=datafinal1.replace({'11.5941,12.3477,13.1013': 11.5941})
datafinal1=datafinal1.replace({'77.5978,77.6001': 77.5978})
datafinal1=datafinal1.replace({'12.8939,12.9106': 12.8939})
datafinal1=datafinal1.replace({'13.0583,13.0597,13.0611':13.0583})
datafinal1

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,560002,49,74.4891,12.9417,53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,560013,9,77.4484,13.11,67,49,34,18,2,7,1,1,Jalahalli
8,560017,0,77.481,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,560020,42,77.492,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,560027,31,77.5489,12.975,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,560030,50,77.5523,12.9299,34,13,13,2,0,0,0,0,Adugodi
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,"560040,560042,560047",0,77.5617,12.902,100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,77.5732,13.0583,21,14,9,5,0,1,0,1,Benson Town
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,77.5896,12.8608,8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,560071,50,77.5963,11.5941,43,20,25,10,1,2,1,0,Domlur
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,560076,98,77.5978,12.8939,72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,560083,62,77.6079,12.944,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.938,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,"77.6209,77.626,77.6279,77.6299","12.8706,12.8931,12.8949,12.924",56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,"560086,560087",50,77.6226,13.036,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,"560090,560093,560094,560095",33,77.6227,12.932,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,560099,28,"77.6804,77.6809","12.8263,12.8311",24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,560100,44,"77.6869,77.7164","12.9923,12.9944",31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,"560102,560104,560109,560110",0,77.7432,12.769,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

In [81]:
datafinal1=datafinal1.replace({'77.6209,77.626,77.6279,77.6299': 77.6209})
datafinal1=datafinal1.replace({'12.8706,12.8931,12.8949,12.924': 12.8706})
datafinal1=datafinal1.replace({'77.6804,77.6809': 77.6804})
datafinal1=datafinal1.replace({'12.8263,12.8311': 12.8263})
datafinal1=datafinal1.replace({'77.6869,77.7164': 77.6869})
datafinal1=datafinal1.replace({'12.9923,12.9944': 12.9923})
datafinal1

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,560002,49,74.4891,12.9417,53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,560013,9,77.4484,13.11,67,49,34,18,2,7,1,1,Jalahalli
8,560017,0,77.481,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,560020,42,77.492,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,560027,31,77.5489,12.975,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,560030,50,77.5523,12.9299,34,13,13,2,0,0,0,0,Adugodi
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,"560040,560042,560047",0,77.5617,12.902,100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,77.5732,13.0583,21,14,9,5,0,1,0,1,Benson Town
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,77.5896,12.8608,8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,560071,50,77.5963,11.5941,43,20,25,10,1,2,1,0,Domlur
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,560076,98,77.5978,12.8939,72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,560083,62,77.6079,12.944,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.938,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,77.6209,12.8706,56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,"560086,560087",50,77.6226,13.036,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,"560090,560093,560094,560095",33,77.6227,12.932,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,560099,28,77.6804,12.8263,24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,560100,44,77.6869,12.9923,31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,"560102,560104,560109,560110",0,77.7432,12.769,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

In [82]:
datafinal1['Longitude']=datafinal1['Longitude'].astype(float)
datafinal1['Latitude']=datafinal1['Latitude'].astype(float)

In [83]:
datafinal1['Number of Food Outlets']=datafinal1['Number of Food Outlets'].astype(int)

In [84]:
k=13
restaurant_clustering =datafinal1.drop(['Pincode','Number of Food Outlets','Area','One','Two','Three','Four','Five','Six','Seven','Eight'],1)
kmeans = KMeans(n_clusters = k,random_state=0).fit(restaurant_clustering)
kmeans.labels_
datafinal1.insert(0, 'Clusters', kmeans.labels_)
data
datafinal1

,Clusters,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
0,1,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."
1,2,560002,49,74.4891,12.9417,53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."
2,3,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."
3,4,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."
4,8,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."
5,5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,5,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."
7,10,560013,9,77.4484,13.1100,67,49,34,18,2,7,1,1,Jalahalli
8,7,560017,0,77.4810,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
9,9,560020,42,77.4920,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,9,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"
11,12,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
13,10,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
14,12,560027,31,77.5489,12.9750,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,12,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
16,7,560030,50,77.5523,12.9299,34,13,13,2,0,0,0,0,Adugodi
17,10,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
18,12,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
19,7,"560040,560042,560047",0,77.5617,12.9020,100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
20,12,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,12,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
22,10,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,10,560046,37,77.5732,13.0583,21,14,9,5,0,1,0,1,Benson Town
24,12,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
25,7,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
26,12,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
27,10,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura
28,7,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,7,560064,11,77.5896,12.8608,8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
30,12,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,12,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
32,7,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
33,6,560071,50,77.5963,11.5941,43,20,25,10,1,2,1,0,Domlur
34,12,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
35,7,560076,98,77.5978,12.8939,72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,7,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,7,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
38,12,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare
39,7,560083,62,77.6079,12.9440,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,7,560084,32,77.6153,12.9380,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,7,560085,74,77.6209,12.8706,56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
42,0,"560086,560087",50,77.6226,13.0360,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
43,7,"560090,560093,560094,560095",33,77.6227,12.9320,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."
44,0,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,0,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,0,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
47,11,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
48,0,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
49,11,560099,28,77.6804,12.8263,24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
50,0,560100,44,77.6869,12.9923,31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
51,11,"560102,560104,560109,560110",0,77.7432,12.7690,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."
52,0,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

In [85]:
C0=datafinal1.loc[datafinal1['Clusters'] == 0, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C0

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
42,"560086,560087",50,77.6226,13.0360,9,11,14,9,4,5,3,1,"Gunjur,Mahalakshmipuram Layout,Muthusandra,Var..."
44,560091,19,77.6374,13.0096,20,5,2,0,0,0,0,0,"Bapagrama,Herohalli,Viswaneedam"
45,560092,53,77.6391,12.9617,51,31,21,8,5,2,4,2,"Amruthahalli,Byatarayanapura,Kodigehalli,Sahak..."
46,560096,22,77.6487,13.0158,100,45,38,12,2,1,0,1,Nandinilayout
48,560098,5,77.6765,12.9255,22,28,27,21,7,2,5,7,"Kenchanahalli,Rajarajeshwarinagar"
50,560100,44,77.6869,12.9923,31,32,33,10,12,6,2,3,"Electronics City,Wipro Limited"
52,560103,33,77.7473,12.9716,66,31,52,31,14,5,3,2,"Bellandur,Panathur"

In [86]:
print('1-50:',C0['One'].sum())
print('51-100:',C0['Two'].sum())
print('101-250:',C0['Three'].sum())
print('251-500:',C0['Four'].sum())
print('501-1000:',C0['Five'].sum())
print('1001-2500:',C0['Six'].sum())
print('2500-5000:',C0['Seven'].sum())
print('5000 & above:',C0['Eight'].sum())
print('Number of Food Outlets:',C0['Number of Food Outlets'].sum())

1-50: 299
51-100: 183
101-250: 187
251-500: 91
501-1000: 44
1001-2500: 21
2500-5000: 17
5000 & above: 16
Number of Food Outlets: 226

In [87]:
C1=datafinal1.loc[datafinal1['Clusters'] == 1, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C1

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
0,560001,31,73.7291,21.4504,36,15,16,7,0,3,0,1,"Bangalore Bazaar,Bangalore G.P.O.,CMM Court Co..."

In [88]:
print('1-50:',C1['One'].sum())
print('51-100:',C1['Two'].sum())
print('101-250:',C1['Three'].sum())
print('251-500:',C1['Four'].sum())
print('501-1000:',C1['Five'].sum())
print('1001-2500:',C1['Six'].sum())
print('2500-5000:',C1['Seven'].sum())
print('5000 & above:',C1['Eight'].sum())
print('Number of Food Outlets:',C1['Number of Food Outlets'].sum())

1-50: 36
51-100: 15
101-250: 16
251-500: 7
501-1000: 0
1001-2500: 3
2500-5000: 0
5000 & above: 1
Number of Food Outlets: 31

In [89]:
C2=datafinal1.loc[datafinal1['Clusters'] == 2, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C2

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
1,560002,49,74.4891,12.9417,53,28,27,10,0,2,1,1,"Bangalore City,Bangalore Corporation Building,..."

In [90]:
print('1-50:',C2['One'].sum())
print('51-100:',C2['Two'].sum())
print('101-250:',C2['Three'].sum())
print('251-500:',C2['Four'].sum())
print('501-1000:',C2['Five'].sum())
print('1001-2500:',C2['Six'].sum())
print('2500-5000:',C2['Seven'].sum())
print('5000 & above:',C2['Eight'].sum())
print('Number of Food Outlets:',C2['Number of Food Outlets'].sum())

1-50: 53
51-100: 28
101-250: 27
251-500: 10
501-1000: 0
1001-2500: 2
2500-5000: 1
5000 & above: 1
Number of Food Outlets: 49

In [91]:
C3=datafinal1.loc[datafinal1['Clusters'] == 3, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C3

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
2,560003,47,76.2752,15.8266,112,63,41,18,5,2,0,2,"Malleswaram,Palace Guttahalli,Swimming Pool Ex..."

In [92]:
print('1-50:',C3['One'].sum())
print('51-100:',C3['Two'].sum())
print('101-250:',C3['Three'].sum())
print('251-500:',C3['Four'].sum())
print('501-1000:',C3['Five'].sum())
print('1001-2500:',C3['Six'].sum())
print('2500-5000:',C3['Seven'].sum())
print('5000 & above:',C3['Eight'].sum())
print('Number of Food Outlets:',C3['Number of Food Outlets'].sum())

1-50: 112
51-100: 63
101-250: 41
251-500: 18
501-1000: 5
1001-2500: 2
2500-5000: 0
5000 & above: 2
Number of Food Outlets: 47

In [93]:
C4=datafinal1.loc[datafinal1['Clusters'] == 4, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C4

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
3,560004,35,76.5761,10.8368,16,8,6,2,1,1,0,0,"Basavanagudi,Mavalli,Pampamahakavi Road,Thyaga..."

In [94]:
print('1-50:',C4['One'].sum())
print('51-100:',C4['Two'].sum())
print('101-250:',C4['Three'].sum())
print('251-500:',C4['Four'].sum())
print('501-1000:',C4['Five'].sum())
print('1001-2500:',C4['Six'].sum())
print('2500-5000:',C4['Seven'].sum())
print('5000 & above:',C4['Eight'].sum())
print('Number of Food Outlets:',C4['Number of Food Outlets'].sum())

1-50: 16
51-100: 8
101-250: 6
251-500: 2
501-1000: 1
1001-2500: 1
2500-5000: 0
5000 & above: 0
Number of Food Outlets: 35

In [95]:
C5=datafinal1.loc[datafinal1['Clusters'] == 5, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C5

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
5,560010,37,76.9627,13.2029,169,85,59,19,4,3,1,1,"Industrial Estate (Bangalore),Rajajinagar,Raja..."
6,"560011,560012,560014,560015,560016,560018,560019",0,77.0942,13.1791,104,64,48,12,5,0,0,1,"Chamrajpet (Bangalore),Doorvaninagar,Gaviopura..."

In [96]:
print('1-50:',C5['One'].sum())
print('51-100:',C5['Two'].sum())
print('101-250:',C5['Three'].sum())
print('251-500:',C5['Four'].sum())
print('501-1000:',C5['Five'].sum())
print('1001-2500:',C5['Six'].sum())
print('2500-5000:',C5['Seven'].sum())
print('5000 & above:',C5['Eight'].sum())
print('Number of Food Outlets:',C5['Number of Food Outlets'].sum())

1-50: 273
51-100: 149
101-250: 107
251-500: 31
501-1000: 9
1001-2500: 3
2500-5000: 1
5000 & above: 2
Number of Food Outlets: 37

In [97]:
C6=datafinal1.loc[datafinal1['Clusters'] == 6, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C6

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
33,560071,50,77.5963,11.5941,43,20,25,10,1,2,1,0,Domlur

In [98]:
print('1-50:',C6['One'].sum())
print('51-100:',C6['Two'].sum())
print('101-250:',C6['Three'].sum())
print('251-500:',C6['Four'].sum())
print('501-1000:',C6['Five'].sum())
print('1001-2500:',C6['Six'].sum())
print('2500-5000:',C6['Seven'].sum())
print('5000 & above:',C6['Eight'].sum())
print('Number of Food Outlets:',C6['Number of Food Outlets'].sum())

1-50: 43
51-100: 20
101-250: 25
251-500: 10
501-1000: 1
1001-2500: 2
2500-5000: 1
5000 & above: 0
Number of Food Outlets: 50

In [99]:
C7=datafinal1.loc[datafinal1['Clusters'] == 7, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C7

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
8,560017,0,77.4810,12.9121,6,4,6,4,0,0,0,1,"NAL,Vimanapura"
16,560030,50,77.5523,12.9299,34,13,13,2,0,0,0,0,Adugodi
19,"560040,560042,560047",0,77.5617,12.9020,100,53,43,14,8,1,0,0,"Austin Town,Chandra Lay Out,Sivan Chetty Garde..."
25,560049,0,77.5798,12.9229,146,68,59,13,3,6,1,0,"Bhattarahalli,Bidrahalli,Mundur,Thambuchetty p..."
28,"560061,560062,560063,560065,560067",0,77.5885,12.9278,38,9,15,5,1,0,0,0,"A F Station Yelahanka,BSF Campus Yelahanka,Chi..."
29,560064,11,77.5896,12.8608,8,4,5,1,0,0,0,0,"Attur,CRPF Campus Yelahanka,Jakkur,Rajanakunte..."
32,"560070,560073,560074,560075,560077,560079",50,77.5952,12.9506,38,30,36,9,7,1,1,2,"B Sk II Stage,Bagalgunte,Basaveshwaranagar,Chi..."
35,560076,98,77.5978,12.8939,72,35,26,10,6,3,2,5,"Bannerghatta Road,Bilekahalli,JP Nagar VIII ph..."
36,560078,57,77.6025,12.9634,93,47,50,16,14,6,1,3,"J P Nagar,JP Nagar III Phase,Kumaraswamy Layou..."
37,560080,37,77.6041,12.9316,22,12,12,4,3,4,0,1,Sadashivanagar
39,560083,62,77.6079,12.9440,13,11,4,0,0,0,0,2,"Bannerghatta,Gottigere"
40,560084,32,77.6153,12.9380,187,113,74,30,13,8,6,6,"Kacharakanahalli,Lingarajapuram,St. Thomas Town"
41,560085,74,77.6209,12.8706,56,39,37,13,6,1,4,1,"Banashankari III Stage,Byatarayanapura,Girinag..."
43,"560090,560093,560094,560095",33,77.6227,12.9320,89,46,27,19,8,5,0,2,"C.V.Raman Nagar,ISRO Anthariksha Bhavan,Korama..."

In [100]:
print('1-50:',C7['One'].sum())
print('51-100:',C7['Two'].sum())
print('101-250:',C7['Three'].sum())
print('251-500:',C7['Four'].sum())
print('501-1000:',C7['Five'].sum())
print('1001-2500:',C7['Six'].sum())
print('2500-5000:',C7['Seven'].sum())
print('5000 & above:',C7['Eight'].sum())
print('Number of Food Outlets:',C7['Number of Food Outlets'].sum())

1-50: 902
51-100: 484
101-250: 407
251-500: 140
501-1000: 69
1001-2500: 35
2500-5000: 15
5000 & above: 23
Number of Food Outlets: 504

In [101]:
C8=datafinal1.loc[datafinal1['Clusters'] == 8, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C8

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
4,"560005,560006,560007,560008,560009",0,76.8024,13.7952,28,15,17,6,7,4,3,2,"Agram,Air Force Hospital,Bangalore Dist Office..."

In [102]:
print('1-50:',C8['One'].sum())
print('51-100:',C8['Two'].sum())
print('101-250:',C8['Three'].sum())
print('251-500:',C8['Four'].sum())
print('501-1000:',C8['Five'].sum())
print('1001-2500:',C8['Six'].sum())
print('2500-5000:',C8['Seven'].sum())
print('5000 & above:',C8['Eight'].sum())
print('Number of Food Outlets:',C8['Number of Food Outlets'].sum())

1-50: 28
51-100: 15
101-250: 17
251-500: 6
501-1000: 7
1001-2500: 4
2500-5000: 3
5000 & above: 2
Number of Food Outlets: 0

In [103]:
C9=datafinal1.loc[datafinal1['Clusters'] == 9, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C9

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
9,560020,42,77.4920,12.6859,88,39,42,9,5,5,2,0,Seshadripuram
10,560021,44,77.5053,12.7717,16,15,11,4,0,0,0,0,"Gayathrinagar,Srirampuram"

In [104]:
print('1-50:',C9['One'].sum())
print('51-100:',C9['Two'].sum())
print('101-250:',C9['Three'].sum())
print('251-500:',C9['Four'].sum())
print('501-1000:',C9['Five'].sum())
print('1001-2500:',C9['Six'].sum())
print('2500-5000:',C9['Seven'].sum())
print('5000 & above:',C9['Eight'].sum())
print('Number of Food Outlets:',C9['Number of Food Outlets'].sum())

1-50: 104
51-100: 54
101-250: 53
251-500: 13
501-1000: 5
1001-2500: 5
2500-5000: 2
5000 & above: 0
Number of Food Outlets: 86

In [105]:
C10=datafinal1.loc[datafinal1['Clusters'] == 10, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C10

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
7,560013,9,77.4484,13.1100,67,49,34,18,2,7,1,1,Jalahalli
13,560025,48,77.5474,13.0448,7,5,7,1,0,0,0,1,"CMP Centre And School,Museum Road,Richmond Town"
17,"560032,560033,560035,560036,560037,560038,560039",50,77.5566,13.0814,16,3,5,1,1,0,0,0,"Carmelram,Devasandra,Doddanekkundi,Indiranagar..."
22,560045,20,77.5732,13.0583,38,8,15,1,0,0,0,0,"Arabic College,Nagawara,Venkateshapura"
23,560046,37,77.5732,13.0583,21,14,9,5,0,1,0,1,Benson Town
27,560060,8,77.5837,13.1195,16,6,5,0,1,0,0,0,Chudenapura

In [106]:
print('1-50:',C10['One'].sum())
print('51-100:',C10['Two'].sum())
print('101-250:',C10['Three'].sum())
print('251-500:',C10['Four'].sum())
print('501-1000:',C10['Five'].sum())
print('1001-2500:',C10['Six'].sum())
print('2500-5000:',C10['Seven'].sum())
print('5000 & above:',C10['Eight'].sum())
print('Number of Food Outlets:',C10['Number of Food Outlets'].sum())

1-50: 165
51-100: 85
101-250: 75
251-500: 26
501-1000: 4
1001-2500: 8
2500-5000: 1
5000 & above: 3
Number of Food Outlets: 172

In [107]:
C11=datafinal1.loc[datafinal1['Clusters'] == 11, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C11

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
47,560097,7,77.6727,12.8458,48,38,35,23,6,6,2,5,"Chikkabettahalli,Vidyaranyapura"
49,560099,28,77.6804,12.8263,24,22,40,11,7,3,2,0,"Bommasandra Industrial Estate,Hebbagodi,Muthan..."
51,"560102,560104,560109,560110",0,77.7432,12.7690,52,29,19,14,6,1,1,0,"HSR Layout,Hampinagar,Thalaghattapura,Ullalu U..."

In [108]:
print('1-50:',C11['One'].sum())
print('51-100:',C11['Two'].sum())
print('101-250:',C11['Three'].sum())
print('251-500:',C11['Four'].sum())
print('501-1000:',C11['Five'].sum())
print('1001-2500:',C11['Six'].sum())
print('2500-5000:',C11['Seven'].sum())
print('5000 & above:',C11['Eight'].sum())
print('Number of Food Outlets:',C11['Number of Food Outlets'].sum())

1-50: 124
51-100: 89
101-250: 94
251-500: 48
501-1000: 19
1001-2500: 10
2500-5000: 5
5000 & above: 5
Number of Food Outlets: 35

In [109]:
C12=datafinal1.loc[datafinal1['Clusters'] == 12, datafinal1.columns[[1] + list(range(2, datafinal1.shape[1]))]]
C12

,Pincode,Number of Food Outlets,Longitude,Latitude,One,Two,Three,Four,Five,Six,Seven,Eight,Area
11,"560022,560024,560026",0,77.5113,12.9801,10,7,7,1,0,0,0,0,"Anandnagar (Bangalore),Deepanjalinagar,Governm..."
12,560023,32,77.5361,13.0134,8,1,7,0,0,0,0,0,Magadi Road
14,560027,31,77.5489,12.9750,3,7,1,2,0,0,0,0,"Sampangiramnagar,Shanthinagar,Wilson Garden"
15,560029,0,77.5491,12.9847,64,31,19,6,6,0,0,1,"Dharmaram College,Tavarekere"
18,560034,50,77.5609,13.0323,201,108,105,38,13,7,4,1,"Agara,Koramangala,Koramangala I Block,St. John..."
20,560041,50,77.5625,12.9879,19,1,1,0,0,0,0,0,"Jayanagar,Tilaknagar (Bangalore)"
21,560043,28,77.5648,13.0097,54,22,16,5,2,1,0,0,"Banaswadi,Horamavu,Jalavayuvihar,Kalyananagar"
24,560048,41,77.5789,12.9879,33,15,8,5,3,0,0,1,"Hoodi,Mahadevapura"
26,"560050,560051,560053,560054,560055,560056,5600...",40,77.5806,13.0104,22,16,13,3,1,2,0,0,"Ashoknagar (Bangalore),Banashankari,Bnagalore ..."
30,560066,22,77.5937,12.9719,47,23,13,6,0,2,0,1,"EPIP,Immedihalli,Ramagondana Halli,Whitefield"
31,560068,95,77.5944,12.9914,157,90,91,54,22,14,8,7,"Begur,Bommanahalli,Hongasandra,Madivala"
34,560072,9,77.5971,13.0068,122,72,51,27,10,0,3,3,Nagarbhavi
38,560082,0,77.6044,12.9985,19,8,2,0,2,0,0,0,Bolare

In [110]:
print('1-50:',C12['One'].sum())
print('51-100:',C12['Two'].sum())
print('101-250:',C12['Three'].sum())
print('251-500:',C12['Four'].sum())
print('501-1000:',C12['Five'].sum())
print('1001-2500:',C12['Six'].sum())
print('2500-5000:',C12['Seven'].sum())
print('5000 & above:',C12['Eight'].sum())
print('Number of Food Outlets:',C12['Number of Food Outlets'].sum())

1-50: 759
51-100: 401
101-250: 334
251-500: 147
501-1000: 59
1001-2500: 26
2500-5000: 15
5000 & above: 14
Number of Food Outlets: 398

In [111]:
L0=C0.One.sum(),C0.Two.sum(),C0.Three.sum(),C0.Four.sum(),C0.Five.sum(),C0.Six.sum(),C0.Seven.sum(),C0.Eight.sum(),C0['Number of Food Outlets'].sum()
L1=C1.One.sum(),C1.Two.sum(),C1.Three.sum(),C1.Four.sum(),C1.Five.sum(),C1.Six.sum(),C1.Seven.sum(),C1.Eight.sum(),C1['Number of Food Outlets'].sum()
L2=C2.One.sum(),C2.Two.sum(),C2.Three.sum(),C2.Four.sum(),C2.Five.sum(),C2.Six.sum(),C2.Seven.sum(),C2.Eight.sum(),C2['Number of Food Outlets'].sum()
L3=C3.One.sum(),C3.Two.sum(),C3.Three.sum(),C3.Four.sum(),C3.Five.sum(),C3.Six.sum(),C3.Seven.sum(),C3.Eight.sum(),C3['Number of Food Outlets'].sum()
L4=C4.One.sum(),C4.Two.sum(),C4.Three.sum(),C4.Four.sum(),C4.Five.sum(),C4.Six.sum(),C4.Seven.sum(),C4.Eight.sum(),C4['Number of Food Outlets'].sum()
L5=C5.One.sum(),C5.Two.sum(),C5.Three.sum(),C5.Four.sum(),C5.Five.sum(),C5.Six.sum(),C5.Seven.sum(),C5.Eight.sum(),C5['Number of Food Outlets'].sum()
L6=C6.One.sum(),C6.Two.sum(),C6.Three.sum(),C6.Four.sum(),C6.Five.sum(),C6.Six.sum(),C6.Seven.sum(),C6.Eight.sum(),C6['Number of Food Outlets'].sum()
L7=C7.One.sum(),C7.Two.sum(),C7.Three.sum(),C7.Four.sum(),C7.Five.sum(),C7.Six.sum(),C7.Seven.sum(),C7.Eight.sum(),C7['Number of Food Outlets'].sum()
L8=C8.One.sum(),C8.Two.sum(),C8.Three.sum(),C8.Four.sum(),C8.Five.sum(),C8.Six.sum(),C8.Seven.sum(),C8.Eight.sum(),C8['Number of Food Outlets'].sum()
L9=C9.One.sum(),C9.Two.sum(),C9.Three.sum(),C9.Four.sum(),C9.Five.sum(),C9.Six.sum(),C9.Seven.sum(),C9.Eight.sum(),C1['Number of Food Outlets'].sum()
L10=C10.One.sum(),C10.Two.sum(),C10.Three.sum(),C10.Four.sum(),C10.Five.sum(),C10.Six.sum(),C10.Seven.sum(),C10.Eight.sum(),C10['Number of Food Outlets'].sum()
L11=C11.One.sum(),C11.Two.sum(),C11.Three.sum(),C11.Four.sum(),C11.Five.sum(),C11.Six.sum(),C11.Seven.sum(),C11.Eight.sum(),C11['Number of Food Outlets'].sum()
L12=C12.One.sum(),C12.Two.sum(),C12.Three.sum(),C12.Four.sum(),C12.Five.sum(),C12.Six.sum(),C12.Seven.sum(),C12.Eight.sum(),C12['Number of Food Outlets'].sum()
LF=pd.DataFrame([L0,L1,L2,L3,L4,L5,L6,L7,L8,L9,L10,L11,L12])
LF

      0    1    2    3   4   5   6   7    8
0   299  183  187   91  44  21  17  16  226
1    36   15   16    7   0   3   0   1   31
2    53   28   27   10   0   2   1   1   49
3   112   63   41   18   5   2   0   2   47
4    16    8    6    2   1   1   0   0   35
5   273  149  107   31   9   3   1   2   37
6    43   20   25   10   1   2   1   0   50
7   902  484  407  140  69  35  15  23  504
8    28   15   17    6   7   4   3   2    0
9   104   54   53   13   5   5   2   0   31
10  165   85   75   26   4   8   1   3  172
11  124   89   94   48  19  10   5   5   35
12  759  401  334  147  59  26  15  14  398

In [112]:
LF.columns=['1-50','51-100','101-250','251-500','501-1000','1001-2500','2501-5000','5000 & above','Number of Food Outlets']
LF.index=['C0','C1','C2','C3','C4','C5','C6','C7','C8','C9','C10','C11','C12']
LF

,1-50,51-100,101-250,251-500,501-1000,1001-2500,2501-5000,5000 & above,Number of Food Outlets
C0,299,183,187,91,44,21,17,16,226
C1,36,15,16,7,0,3,0,1,31
C2,53,28,27,10,0,2,1,1,49
C3,112,63,41,18,5,2,0,2,47
C4,16,8,6,2,1,1,0,0,35
C5,273,149,107,31,9,3,1,2,37
C6,43,20,25,10,1,2,1,0,50
C7,902,484,407,140,69,35,15,23,504
C8,28,15,17,6,7,4,3,2,0
C9,104,54,53,13,5,5,2,0,31
C10,165,85,75,26,4,8,1,3,172
C11,124,89,94,48,19,10,5,5,35
C12,759,401,334,147,59,26,15,14,398

4.Visualizing the clusters

In [113]:
import matplotlib.cm as cm
import matplotlib.colors as colors

In [115]:
!conda install -c conda-forge folium=0.5.0 --yes

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.6.20          |   py36h9f0ad1d_0         151 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    branca-0.4.1               |             py_0          26 KB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    ca-certificates-2020.6.20  |       hecda079_0         145 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    openssl-1.1.1g             |       h516909a_0         2.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

    altair:          4.1.0-py_1        conda-forge
    branca:          0.4.1-py_0        conda-forge
    folium:          0.5.0-py_0        conda-forge
    python_abi:      3.6-1_cp36m       conda-forge
    vincent:         0.4.4-py_1        conda-forge

The following packages will be UPDATED:

    certifi:         2020.6.20-py36_0              --> 2020.6.20-py36h9f0ad1d_0 conda-forge
    openssl:         1.1.1g-h7b6447c_0             --> 1.1.1g-h516909a_0        conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2020.6.24-0                   --> 2020.6.20-hecda079_0     conda-forge


Downloading and Extracting Packages
certifi-2020.6.20    | 151 KB    | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
branca-0.4.1         | 26 KB     | ##################################### | 100%
python_abi-3.6       | 4 KB      | ##################################### | 100%
ca-certificates-2020 | 145 KB    | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
vincent-0.4.4        | 28 KB     | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [116]:
import folium

In [122]:
map_clusters = folium.Map(location=[12.9716,77.5946],zoom_start=10)

# set color scheme for the clusters
x = np.arange(k)
ys = [i + x + (i*x)**2 for i in range(k)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, area, cluster in zip(datafinal1['Latitude'], datafinal1['Longitude'], datafinal1['Area'], datafinal1['Clusters']):
    label = folium.Popup(' Clusters ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

4. Discussion:From the resultant dataframe consisting of 13 clusters (generated using K-means clustering algorithm), cluster5 (C5-marked with a red square) was identified as a potential cluster corresponding to Areas in Bangalore (Rajajinagar, Industrial Estate (Bangalore),Rajajinagar IVth Block, Jayangar III Block, Madhavan Park, Science Institute, Jalahalli East, Jalahalli West, Krishnarajapuram R S, Doorvaninagar, Ramamurthy Nagar, Chamrajpet (Bangalore), Gaviopuram Extension having significant number of companies with considerable employee sizes and low number of food outlets. The suggested areas possess the respective pincodes: 560010, 560010, 560011, 560011, 560012, 560014, 560015, 560016, 560016, 560016, 560018, 560019.These are potential areas where a customer can open a restaurant.

5. Conclusion: Geographical location data, pincodes, employee sizes and company data, location data of food outlets by Foursquare and K-means clustering algorithm were used to help a customer identify potential areas/neighborhoods in Bangalore to open a restaurant.